services:
  db:
    image: postgres:16
    container_name: selune_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rpg_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - selune_data:/var/lib/postgresql/data
      - ./postgre.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: selune_app
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      DB_HOST: db

volumes:
  selune_data: