-- ================= ATTRIBUTES =================
INSERT INTO attributes (nome, descricao) VALUES
('hp_maximo', 'Aumenta o HP máximo do jogador'),
('mana_maxima', 'Aumenta a mana máxima'),
('ataque', 'Aumenta o ataque do jogador'),
('armadura', 'Aumenta a armadura do jogador'),
('critico', 'Aumenta a chance de acerto crítico'),
('dano_critico', 'Aumenta o dano causado por críticos'),
('esquiva', 'Chance de evitar um ataque'),
('precisao', 'Reduz a chance de errar ataques'),
('velocidade', 'Determina quem ataca primeiro e influencia algumas habilidades'),
('roubo_vida', 'Recupera HP proporcional ao dano causado'),
('mana_por_turno', 'Regenera mana a cada turno'),
('hp_por_turno', 'Regenera HP a cada turno'),
('xp', 'Aumenta o XP recebido'),
('ouro', 'Aumenta o ouro recebido'),
('resistencia_fogo', 'Reduz dano de fogo'),
('resistencia_gelo', 'Reduz dano de gelo'),
('resistencia_raio', 'Reduz dano elétrico'),
('resistencia_veneno', 'Reduz dano de veneno'),
('resistencia_trevas', 'Reduz dano de trevas'),
('resistencia_luz', 'Reduz dano de luz');

-- ================= ITEMS: CONSUMIVEIS =================
INSERT INTO items (nome, tipo, valor, nivel_requerido, raridade, descricao, funcao) VALUES
('Poção de Cura Menor', 'Consumivel', 20, 1, 'Comum', 'Recupera 10 de HP.', 'curar_10'),
('Poção de Cura', 'Consumivel', 45, 5, 'Comum', 'Recupera 25 de HP.', 'curar_25'),
('Poção de Cura Superior', 'Consumivel', 120, 12, 'Incomum', 'Recupera 50 de HP.', 'curar_50'),
('Poção de Cura Suprema', 'Consumivel', 350, 22, 'Raro', 'Recupera totalmente a vida.', 'curar_total'),
('Poção de Mana Menor', 'Consumivel', 30, 3, 'Comum', 'Recupera 15 de mana.', 'mana_15'),
('Poção de Mana Superior', 'Consumivel', 100, 10, 'Incomum', 'Recupera 40 de mana.', 'mana_40'),
('Elixir da Força', 'Consumivel', 250, 18, 'Raro', 'Aumenta o ataque por um combate.', 'buff_ataque'),
('Tônico Defensivo', 'Consumivel', 250, 18, 'Raro', 'Aumenta a armadura por um combate.', 'buff_armadura'),
('Poção da Experiência', 'Consumivel', 500, 30, 'Épico', 'Concede experiência adicional.', 'bonus_xp'),
('Elixir do Herói', 'Consumivel', 1200, 45, 'Lendário', 'Restaura totalmente HP e mana e fortalece o usuário.', 'elixir_heroi');

-- ================= ITEMS: ARMADURAS =================
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, armadura, raridade) VALUES
('Túnica de Linho', 'Armadura', 40, 1, 'Uma túnica simples.', 2, 'Comum'),
('Colete de Couro', 'Armadura', 80, 2, 'Colete leve.', 4, 'Comum'),
('Couro Reforçado', 'Armadura', 150, 4, 'Couro resistente.', 6, 'Comum'),
('Peitoral de Bronze', 'Armadura', 260, 6, 'Bronze polido.', 9, 'Incomum'),
('Armadura de Bronze', 'Armadura', 420, 8, 'Conjunto de bronze.', 12, 'Incomum'),
('Cota de Malha', 'Armadura', 650, 10, 'Malha metálica.', 15, 'Incomum'),
('Peitoral de Ferro', 'Armadura', 950, 12, 'Ferro refinado.', 18, 'Incomum'),
('Armadura de Ferro', 'Armadura', 1300, 14, 'Armadura militar.', 22, 'Raro'),
('Armadura do Guarda', 'Armadura', 1700, 16, 'Equipamento da guarda.', 26, 'Raro'),
('Peitoral de Aço', 'Armadura', 2200, 18, 'Aço temperado.', 30, 'Raro'),
('Armadura de Aço', 'Armadura', 2800, 20, 'Proteção pesada.', 34, 'Raro'),
('Armadura Escamada', 'Armadura', 3400, 22, 'Escamas metálicas.', 38, 'Raro'),
('Armadura do Cavaleiro', 'Armadura', 4200, 24, 'Usada por cavaleiros.', 42, 'Épico'),
('Armadura Prateada', 'Armadura', 5200, 26, 'Prata encantada.', 46, 'Épico'),
('Armadura de Mithril', 'Armadura', 6500, 28, 'Metal extremamente leve.', 50, 'Épico'),
('Armadura Sagrada', 'Armadura', 7900, 30, 'Abençoada pelos deuses.', 55, 'Épico'),
('Armadura do Paladino', 'Armadura', 9500, 32, 'Proteção divina.', 60, 'Épico'),
('Armadura Dracônica', 'Armadura', 11500, 34, 'Escamas de dragão.', 66, 'Lendário'),
('Armadura de Obsidiana', 'Armadura', 13800, 36, 'Rocha vulcânica.', 72, 'Lendário'),
('Armadura de Adamantium', 'Armadura', 17000, 38, 'Metal praticamente indestrutível.', 80, 'Lendário'),
('Vestes do Sábio', 'Armadura', 18500, 40, 'Vestes mágicas.', 60, 'Épico'),
('Manto Celestial', 'Armadura', 20000, 42, 'Manto sagrado.', 63, 'Épico'),
('Couraça Imperial', 'Armadura', 21800, 44, 'Usada por imperadores.', 82, 'Lendário'),
('Armadura do General', 'Armadura', 23600, 46, 'Símbolo militar.', 85, 'Lendário'),
('Armadura Glacial', 'Armadura', 25500, 48, 'Gelo eterno.', 88, 'Lendário'),
('Armadura Flamejante', 'Armadura', 27500, 50, 'Forjada em magma.', 91, 'Lendário'),
('Armadura Sombria', 'Armadura', 29600, 52, 'Trevas eternas.', 94, 'Lendário'),
('Armadura da Tempestade', 'Armadura', 31800, 54, 'Poder dos céus.', 97, 'Lendário'),
('Armadura Solar', 'Armadura', 34100, 56, 'Energia do sol.', 100, 'Lendário'),
('Armadura Lunar', 'Armadura', 36500, 58, 'Energia da lua.', 103, 'Lendário'),
('Armadura do Titã', 'Armadura', 39000, 60, 'Gigantes antigos.', 107, 'Mítico'),
('Armadura do Guardião', 'Armadura', 41600, 62, 'Guardiões ancestrais.', 111, 'Mítico'),
('Armadura do Dragão Negro', 'Armadura', 44300, 64, 'Escamas negras.', 115, 'Mítico'),
('Armadura do Dragão Branco', 'Armadura', 47100, 66, 'Escamas congeladas.', 119, 'Mítico'),
('Armadura do Dragão Vermelho', 'Armadura', 50000, 68, 'Escamas flamejantes.', 123, 'Mítico'),
('Armadura Celestial', 'Armadura', 53000, 70, 'Forjada nos céus.', 127, 'Mítico'),
('Armadura Abissal', 'Armadura', 56100, 72, 'Profundezas.', 131, 'Mítico'),
('Armadura Arcana', 'Armadura', 59300, 74, 'Energia mágica.', 135, 'Mítico'),
('Armadura do Destino', 'Armadura', 62600, 76, 'Tecida pelo destino.', 140, 'Mítico'),
('Armadura da Eternidade', 'Armadura', 66000, 78, 'Tempo infinito.', 145, 'Mítico'),
('Couraça do Deus da Guerra', 'Armadura', 69500, 80, 'Vestida por um deus.', 150, 'Artefato'),
('Armadura dos Antigos', 'Armadura', 73100, 82, 'Relíquia esquecida.', 155, 'Artefato'),
('Armadura Primordial', 'Armadura', 76800, 84, 'Origem do mundo.', 160, 'Artefato'),
('Armadura do Vazio', 'Armadura', 80600, 86, 'Poder do vazio.', 165, 'Artefato'),
('Armadura Cósmica', 'Armadura', 84500, 88, 'Entre estrelas.', 170, 'Artefato'),
('Armadura do Criador', 'Armadura', 88500, 90, 'Primeira armadura.', 176, 'Artefato'),
('Armadura do Caos', 'Armadura', 92600, 92, 'Energia caótica.', 182, 'Artefato'),
('Armadura da Ordem', 'Armadura', 96800, 94, 'Símbolo da ordem.', 188, 'Artefato'),
('Armadura do Infinito', 'Armadura', 101100, 96, 'Sem limites.', 194, 'Artefato'),
('Armadura de Selune', 'Armadura', 110000, 100, 'A armadura suprema.', 200, 'Relíquia');

-- ================= ITEM_EFFECTS: ARMADURAS =================
INSERT INTO item_effects (item_id, attribute_id, valor, percentual) VALUES
((SELECT id FROM items WHERE nome='Cota de Malha'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 10, FALSE),
((SELECT id FROM items WHERE nome='Armadura de Ferro'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 2, FALSE),
((SELECT id FROM items WHERE nome='Peitoral de Aço'), (SELECT id FROM attributes WHERE nome='xp'), 2, TRUE),
((SELECT id FROM items WHERE nome='Armadura Escamada'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 5, FALSE),
((SELECT id FROM items WHERE nome='Armadura do Cavaleiro'), (SELECT id FROM attributes WHERE nome='critico'), 3, TRUE),
((SELECT id FROM items WHERE nome='Armadura Prateada'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 5, FALSE),
((SELECT id FROM items WHERE nome='Armadura de Mithril'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 5, FALSE),
((SELECT id FROM items WHERE nome='Armadura Dracônica'), (SELECT id FROM attributes WHERE nome='dano_critico'), 5, TRUE),
((SELECT id FROM items WHERE nome='Armadura de Obsidiana'), (SELECT id FROM attributes WHERE nome='ouro'), 10, FALSE),
((SELECT id FROM items WHERE nome='Armadura de Adamantium'), (SELECT id FROM attributes WHERE nome='resistencia_raio'), 4, TRUE),
((SELECT id FROM items WHERE nome='Vestes do Sábio'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 40, FALSE),
((SELECT id FROM items WHERE nome='Manto Celestial'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 15, FALSE),
((SELECT id FROM items WHERE nome='Couraça Imperial'), (SELECT id FROM attributes WHERE nome='xp'), 5, TRUE),
((SELECT id FROM items WHERE nome='Armadura do General'), (SELECT id FROM attributes WHERE nome='ouro'), 15, FALSE),
((SELECT id FROM items WHERE nome='Armadura Glacial'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 15, FALSE),
((SELECT id FROM items WHERE nome='Armadura Flamejante'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 15, FALSE),
((SELECT id FROM items WHERE nome='Armadura Sombria'), (SELECT id FROM attributes WHERE nome='resistencia_veneno'), 5, TRUE),
((SELECT id FROM items WHERE nome='Armadura da Tempestade'), (SELECT id FROM attributes WHERE nome='dano_critico'), 10, TRUE),
((SELECT id FROM items WHERE nome='Armadura Solar'), (SELECT id FROM attributes WHERE nome='critico'), 5, TRUE),
((SELECT id FROM items WHERE nome='Armadura Lunar'), (SELECT id FROM attributes WHERE nome='resistencia_raio'), 6, TRUE),
((SELECT id FROM items WHERE nome='Armadura do Titã'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 60, FALSE),
((SELECT id FROM items WHERE nome='Armadura do Guardião'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 25, FALSE),
((SELECT id FROM items WHERE nome='Armadura do Dragão Negro'), (SELECT id FROM attributes WHERE nome='critico'), 8, TRUE),
((SELECT id FROM items WHERE nome='Armadura do Dragão Branco'), (SELECT id FROM attributes WHERE nome='dano_critico'), 12, TRUE),
((SELECT id FROM items WHERE nome='Armadura do Dragão Vermelho'), (SELECT id FROM attributes WHERE nome='xp'), 8, TRUE),
((SELECT id FROM items WHERE nome='Armadura Celestial'), (SELECT id FROM attributes WHERE nome='ouro'), 20, FALSE),
((SELECT id FROM items WHERE nome='Armadura Abissal'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 20, FALSE),
((SELECT id FROM items WHERE nome='Armadura Arcana'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 20, FALSE),
((SELECT id FROM items WHERE nome='Armadura do Destino'), (SELECT id FROM attributes WHERE nome='resistencia_raio'), 8, TRUE),
((SELECT id FROM items WHERE nome='Armadura da Eternidade'), (SELECT id FROM attributes WHERE nome='resistencia_veneno'), 8, TRUE),
((SELECT id FROM items WHERE nome='Couraça do Deus da Guerra'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 80, FALSE),
((SELECT id FROM items WHERE nome='Armadura dos Antigos'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 30, FALSE),
((SELECT id FROM items WHERE nome='Armadura Primordial'), (SELECT id FROM attributes WHERE nome='critico'), 10, TRUE),
((SELECT id FROM items WHERE nome='Armadura do Vazio'), (SELECT id FROM attributes WHERE nome='dano_critico'), 15, TRUE),
((SELECT id FROM items WHERE nome='Armadura Cósmica'), (SELECT id FROM attributes WHERE nome='xp'), 10, TRUE),
((SELECT id FROM items WHERE nome='Armadura do Criador'), (SELECT id FROM attributes WHERE nome='ouro'), 30, FALSE),
((SELECT id FROM items WHERE nome='Armadura do Caos'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 30, FALSE),
((SELECT id FROM items WHERE nome='Armadura da Ordem'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 30, FALSE),
((SELECT id FROM items WHERE nome='Armadura do Infinito'), (SELECT id FROM attributes WHERE nome='resistencia_raio'), 10, TRUE),
((SELECT id FROM items WHERE nome='Armadura de Selune'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 150, FALSE),
((SELECT id FROM items WHERE nome='Armadura de Selune'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 50, FALSE),
((SELECT id FROM items WHERE nome='Armadura de Selune'), (SELECT id FROM attributes WHERE nome='critico'), 15, TRUE),
((SELECT id FROM items WHERE nome='Armadura de Selune'), (SELECT id FROM attributes WHERE nome='dano_critico'), 20, TRUE),
((SELECT id FROM items WHERE nome='Armadura de Selune'), (SELECT id FROM attributes WHERE nome='xp'), 15, TRUE),
((SELECT id FROM items WHERE nome='Armadura de Selune'), (SELECT id FROM attributes WHERE nome='resistencia_raio'), 15, TRUE),
((SELECT id FROM items WHERE nome='Armadura de Selune'), (SELECT id FROM attributes WHERE nome='resistencia_veneno'), 15, TRUE);

-- ================= ITEMS: ARMAS =================
INSERT INTO items (nome, tipo, valor, nivel_requerido, raridade, descricao, dano) VALUES
('Adaga Enferrujada', 'Arma', 30, 1, 'Comum', 'Uma arma do tipo arma.', 3),
('Espada Curta', 'Arma', 70, 2, 'Comum', 'Uma arma do tipo arma.', 5),
('Machado de Lenhador', 'Arma', 120, 4, 'Comum', 'Uma arma do tipo arma.', 8),
('Lança de Madeira', 'Arma', 180, 6, 'Incomum', 'Uma arma do tipo arma.', 11),
('Espada de Bronze', 'Arma', 260, 8, 'Incomum', 'Uma arma do tipo arma.', 14),
('Martelo de Guerra', 'Arma', 380, 10, 'Incomum', 'Uma arma do tipo arma.', 18),
('Espada Longa', 'Arma', 550, 12, 'Incomum', 'Uma arma do tipo arma.', 22),
('Machado de Ferro', 'Arma', 780, 14, 'Raro', 'Uma arma do tipo arma.', 27),
('Lança de Ferro', 'Arma', 1050, 16, 'Raro', 'Uma arma do tipo arma.', 32),
('Sabre do Guarda', 'Arma', 1350, 18, 'Raro', 'Uma arma do tipo arma.', 37),
('Espada de Aço', 'Arma', 1750, 20, 'Raro', 'Uma arma do tipo arma.', 42),
('Machado de Batalha', 'Arma', 2200, 22, 'Raro', 'Uma arma do tipo arma.', 47),
('Espada do Cavaleiro', 'Arma', 2750, 24, 'Épico', 'Uma arma do tipo arma.', 53),
('Alabarda Imperial', 'Arma', 3400, 26, 'Épico', 'Uma arma do tipo arma.', 59),
('Espada de Mithril', 'Arma', 4200, 28, 'Épico', 'Uma arma do tipo arma.', 66),
('Martelo Sagrado', 'Arma', 5100, 30, 'Épico', 'Uma arma do tipo arma.', 73),
('Lança Celestial', 'Arma', 6200, 32, 'Épico', 'Uma arma do tipo arma.', 80),
('Espada Dracônica', 'Arma', 7500, 34, 'Lendário', 'Uma arma do tipo arma.', 88),
('Foice Sombria', 'Arma', 9000, 36, 'Lendário', 'Uma arma do tipo arma.', 96),
('Espada de Adamantium', 'Arma', 10800, 38, 'Lendário', 'Uma arma do tipo arma.', 105),
('Katana do Vento', 'Arma', 12500, 40, 'Épico', 'Uma arma do tipo arma.', 110),
('Arco Élfico', 'Arma', 14200, 42, 'Épico', 'Uma arma do tipo arma.', 116),
('Besta Reforçada', 'Arma', 16000, 44, 'Lendário', 'Uma arma do tipo arma.', 122),
('Espada Flamejante', 'Arma', 17900, 46, 'Lendário', 'Uma arma do tipo arma.', 128),
('Machado Glacial', 'Arma', 19900, 48, 'Lendário', 'Uma arma do tipo arma.', 134),
('Lança da Tempestade', 'Arma', 22000, 50, 'Lendário', 'Uma arma do tipo arma.', 141),
('Espada Solar', 'Arma', 24200, 52, 'Lendário', 'Uma arma do tipo arma.', 148),
('Espada Lunar', 'Arma', 26500, 54, 'Lendário', 'Uma arma do tipo arma.', 155),
('Foice Abissal', 'Arma', 28900, 56, 'Lendário', 'Uma arma do tipo arma.', 162),
('Martelo dos Titãs', 'Arma', 31400, 58, 'Lendário', 'Uma arma do tipo arma.', 170),
('Espada do Guardião', 'Arma', 34000, 60, 'Mítico', 'Uma arma do tipo arma.', 178),
('Arco Celestial', 'Arma', 36700, 62, 'Mítico', 'Uma arma do tipo arma.', 186),
('Katana Negra', 'Arma', 39500, 64, 'Mítico', 'Uma arma do tipo arma.', 194),
('Machado do Dragão', 'Arma', 42400, 66, 'Mítico', 'Uma arma do tipo arma.', 202),
('Espada Primordial', 'Arma', 45400, 68, 'Mítico', 'Uma arma do tipo arma.', 211),
('Lança do Caos', 'Arma', 48500, 70, 'Mítico', 'Uma arma do tipo arma.', 220),
('Foice da Ordem', 'Arma', 51700, 72, 'Mítico', 'Uma arma do tipo arma.', 229),
('Espada Arcana', 'Arma', 55000, 74, 'Mítico', 'Uma arma do tipo arma.', 238),
('Martelo do Destino', 'Arma', 58400, 76, 'Mítico', 'Uma arma do tipo arma.', 248),
('Espada da Eternidade', 'Arma', 61900, 78, 'Mítico', 'Uma arma do tipo arma.', 258),
('Lâmina Divina', 'Arma', 65500, 80, 'Artefato', 'Uma arma do tipo arma.', 268),
('Espada dos Antigos', 'Arma', 69200, 82, 'Artefato', 'Uma arma do tipo arma.', 279),
('Espada do Vazio', 'Arma', 73000, 84, 'Artefato', 'Uma arma do tipo arma.', 290),
('Lança Cósmica', 'Arma', 76900, 86, 'Artefato', 'Uma arma do tipo arma.', 301),
('Martelo do Criador', 'Arma', 80900, 88, 'Artefato', 'Uma arma do tipo arma.', 313),
('Espada do Infinito', 'Arma', 85000, 90, 'Artefato', 'Uma arma do tipo arma.', 325),
('Katana Celestial', 'Arma', 89200, 92, 'Artefato', 'Uma arma do tipo arma.', 337),
('Foice do Apocalipse', 'Arma', 93500, 94, 'Artefato', 'Uma arma do tipo arma.', 350),
('Espada do Universo', 'Arma', 97900, 96, 'Artefato', 'Uma arma do tipo arma.', 364),
('Lâmina de Selune', 'Arma', 110000, 100, 'Relíquia', 'Uma arma do tipo arma.', 380);

-- ================= ITEM_EFFECTS: ARMAS =================
INSERT INTO item_effects (item_id, attribute_id, valor, percentual) VALUES
((SELECT id FROM items WHERE nome='Espada de Bronze'), (SELECT id FROM attributes WHERE nome='critico'), 2, TRUE),
((SELECT id FROM items WHERE nome='Espada Longa'), (SELECT id FROM attributes WHERE nome='ataque'), 4, FALSE),
((SELECT id FROM items WHERE nome='Sabre do Guarda'), (SELECT id FROM attributes WHERE nome='precisao'), 3, TRUE),
((SELECT id FROM items WHERE nome='Espada de Aço'), (SELECT id FROM attributes WHERE nome='critico'), 4, TRUE),
((SELECT id FROM items WHERE nome='Machado de Batalha'), (SELECT id FROM attributes WHERE nome='dano_critico'), 8, TRUE),
((SELECT id FROM items WHERE nome='Espada do Cavaleiro'), (SELECT id FROM attributes WHERE nome='critico'), 5, TRUE),
((SELECT id FROM items WHERE nome='Alabarda Imperial'), (SELECT id FROM attributes WHERE nome='ataque'), 10, FALSE),
((SELECT id FROM items WHERE nome='Espada de Mithril'), (SELECT id FROM attributes WHERE nome='precisao'), 5, TRUE),
((SELECT id FROM items WHERE nome='Martelo Sagrado'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 3, TRUE),
((SELECT id FROM items WHERE nome='Lança Celestial'), (SELECT id FROM attributes WHERE nome='velocidade'), 5, TRUE),
((SELECT id FROM items WHERE nome='Espada Dracônica'), (SELECT id FROM attributes WHERE nome='dano_critico'), 15, TRUE),
((SELECT id FROM items WHERE nome='Foice Sombria'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 5, TRUE),
((SELECT id FROM items WHERE nome='Espada de Adamantium'), (SELECT id FROM attributes WHERE nome='critico'), 8, TRUE),
((SELECT id FROM items WHERE nome='Espada Flamejante'), (SELECT id FROM attributes WHERE nome='ataque'), 15, FALSE),
((SELECT id FROM items WHERE nome='Machado Glacial'), (SELECT id FROM attributes WHERE nome='dano_critico'), 20, TRUE),
((SELECT id FROM items WHERE nome='Lança da Tempestade'), (SELECT id FROM attributes WHERE nome='velocidade'), 8, TRUE),
((SELECT id FROM items WHERE nome='Espada Solar'), (SELECT id FROM attributes WHERE nome='critico'), 10, TRUE),
((SELECT id FROM items WHERE nome='Espada Lunar'), (SELECT id FROM attributes WHERE nome='precisao'), 10, TRUE),
((SELECT id FROM items WHERE nome='Foice Abissal'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 8, TRUE),
((SELECT id FROM items WHERE nome='Martelo dos Titãs'), (SELECT id FROM attributes WHERE nome='dano_critico'), 25, TRUE),
((SELECT id FROM items WHERE nome='Espada do Guardião'), (SELECT id FROM attributes WHERE nome='ataque'), 20, FALSE),
((SELECT id FROM items WHERE nome='Arco Celestial'), (SELECT id FROM attributes WHERE nome='critico'), 12, TRUE),
((SELECT id FROM items WHERE nome='Katana Negra'), (SELECT id FROM attributes WHERE nome='precisao'), 12, TRUE),
((SELECT id FROM items WHERE nome='Machado do Dragão'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 10, TRUE),
((SELECT id FROM items WHERE nome='Espada Primordial'), (SELECT id FROM attributes WHERE nome='dano_critico'), 30, TRUE),
((SELECT id FROM items WHERE nome='Lança do Caos'), (SELECT id FROM attributes WHERE nome='ataque'), 25, FALSE),
((SELECT id FROM items WHERE nome='Foice da Ordem'), (SELECT id FROM attributes WHERE nome='velocidade'), 10, TRUE),
((SELECT id FROM items WHERE nome='Espada Arcana'), (SELECT id FROM attributes WHERE nome='critico'), 15, TRUE),
((SELECT id FROM items WHERE nome='Martelo do Destino'), (SELECT id FROM attributes WHERE nome='mana_por_turno'), 8, FALSE),
((SELECT id FROM items WHERE nome='Espada da Eternidade'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 12, TRUE),
((SELECT id FROM items WHERE nome='Lâmina Divina'), (SELECT id FROM attributes WHERE nome='dano_critico'), 35, TRUE),
((SELECT id FROM items WHERE nome='Espada dos Antigos'), (SELECT id FROM attributes WHERE nome='critico'), 18, TRUE),
((SELECT id FROM items WHERE nome='Espada do Vazio'), (SELECT id FROM attributes WHERE nome='ataque'), 30, FALSE),
((SELECT id FROM items WHERE nome='Lança Cósmica'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 15, TRUE),
((SELECT id FROM items WHERE nome='Martelo do Criador'), (SELECT id FROM attributes WHERE nome='precisao'), 15, TRUE),
((SELECT id FROM items WHERE nome='Espada do Infinito'), (SELECT id FROM attributes WHERE nome='dano_critico'), 40, TRUE),
((SELECT id FROM items WHERE nome='Katana Celestial'), (SELECT id FROM attributes WHERE nome='critico'), 20, TRUE),
((SELECT id FROM items WHERE nome='Foice do Apocalipse'), (SELECT id FROM attributes WHERE nome='velocidade'), 15, TRUE),
((SELECT id FROM items WHERE nome='Espada do Universo'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 18, TRUE),
((SELECT id FROM items WHERE nome='Lâmina de Selune'), (SELECT id FROM attributes WHERE nome='ataque'), 50, FALSE),
((SELECT id FROM items WHERE nome='Lâmina de Selune'), (SELECT id FROM attributes WHERE nome='critico'), 25, TRUE),
((SELECT id FROM items WHERE nome='Lâmina de Selune'), (SELECT id FROM attributes WHERE nome='dano_critico'), 60, TRUE),
((SELECT id FROM items WHERE nome='Lâmina de Selune'), (SELECT id FROM attributes WHERE nome='velocidade'), 20, TRUE),
((SELECT id FROM items WHERE nome='Lâmina de Selune'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 20, TRUE),
((SELECT id FROM items WHERE nome='Lâmina de Selune'), (SELECT id FROM attributes WHERE nome='xp'), 15, TRUE);
-- ================= ITEMS: ACESSORIOS =================
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, raridade, subtipo) VALUES
('Anel de Cobre', 'Acessorio', 30, 1, 'Um anel simples de cobre.', 'Comum', 'Anel'),
('Colar de Osso', 'Acessorio', 90, 3, 'Colar feito de ossos de animais.', 'Comum', 'Colar'),
('Amuleto de Pedra', 'Acessorio', 150, 5, 'Amuleto rústico de pedra.', 'Comum', 'Amuleto'),
('Brinco de Latão', 'Acessorio', 210, 7, 'Brinco simples de latão.', 'Comum', 'Brinco'),
('Anel de Prata Simples', 'Acessorio', 270, 9, 'Anel de prata sem lapidação.', 'Comum', 'Anel'),
('Colar de Couro', 'Acessorio', 330, 11, 'Colar trançado em couro.', 'Comum', 'Colar'),
('Amuleto do Viajante', 'Acessorio', 450, 13, 'Usado por viajantes de longa distância.', 'Incomum', 'Amuleto'),
('Brinco de Jade', 'Acessorio', 600, 15, 'Brinco entalhado em jade.', 'Incomum', 'Brinco'),
('Anel do Caçador', 'Acessorio', 750, 17, 'Anel usado por caçadores experientes.', 'Incomum', 'Anel'),
('Colar de Turquesa', 'Acessorio', 900, 19, 'Colar com pedra turquesa polida.', 'Incomum', 'Colar'),
('Amuleto da Sorte', 'Acessorio', 1050, 21, 'Diz-se que traz sorte ao portador.', 'Incomum', 'Amuleto'),
('Brinco de Ônix', 'Acessorio', 1200, 23, 'Brinco com pedra de ônix negro.', 'Incomum', 'Brinco'),
('Anel do Guerreiro', 'Acessorio', 1500, 25, 'Forjado para guerreiros em combate.', 'Raro', 'Anel'),
('Colar do Mago', 'Acessorio', 1800, 27, 'Canaliza energia arcana.', 'Raro', 'Colar'),
('Amuleto Rúnico', 'Acessorio', 2100, 29, 'Gravado com runas antigas.', 'Raro', 'Amuleto'),
('Brinco Élfico', 'Acessorio', 2400, 31, 'Artesanato élfico refinado.', 'Raro', 'Brinco'),
('Anel de Safira', 'Acessorio', 2700, 33, 'Anel com safira lapidada.', 'Raro', 'Anel'),
('Colar de Rubi', 'Acessorio', 3000, 35, 'Colar com rubi vibrante.', 'Raro', 'Colar'),
('Amuleto do Vento', 'Acessorio', 3300, 37, 'Leve como o vento.', 'Raro', 'Amuleto'),
('Anel do Campeão', 'Acessorio', 4200, 39, 'Usado por campeões de arena.', 'Épico', 'Anel'),
('Colar da Fênix', 'Acessorio', 4700, 41, 'Carrega um fragmento de calor eterno.', 'Épico', 'Colar'),
('Amuleto Sagrado', 'Acessorio', 5200, 43, 'Abençoado por um clérigo antigo.', 'Épico', 'Amuleto'),
('Brinco Arcano', 'Acessorio', 5700, 45, 'Pulsa com energia mágica.', 'Épico', 'Brinco'),
('Anel da Tempestade', 'Acessorio', 6200, 47, 'Crepita com eletricidade estática.', 'Épico', 'Anel'),
('Colar Dracônico', 'Acessorio', 6700, 49, 'Feito de escamas de dragão.', 'Épico', 'Colar'),
('Amuleto do Vazio', 'Acessorio', 7200, 51, 'Absorve pequenas frações de escuridão.', 'Épico', 'Amuleto'),
('Anel do Titã', 'Acessorio', 8500, 53, 'Forjado pelos titãs antigos.', 'Lendário', 'Anel'),
('Colar Celestial', 'Acessorio', 9200, 55, 'Brilha com luz dos céus.', 'Lendário', 'Colar'),
('Amuleto Solar', 'Acessorio', 9900, 57, 'Contém o calor do sol.', 'Lendário', 'Amuleto'),
('Brinco Lunar', 'Acessorio', 10600, 59, 'Reflete a luz da lua.', 'Lendário', 'Brinco'),
('Anel Glacial', 'Acessorio', 11300, 61, 'Eternamente frio ao toque.', 'Lendário', 'Anel'),
('Colar Flamejante', 'Acessorio', 12000, 63, 'Nunca esfria completamente.', 'Lendário', 'Colar'),
('Amuleto Sombrio', 'Acessorio', 12700, 65, 'Envolto em trevas antigas.', 'Lendário', 'Amuleto'),
('Anel do Guardião', 'Acessorio', 15000, 67, 'Usado por guardiões ancestrais.', 'Mítico', 'Anel'),
('Colar do Destino', 'Acessorio', 16000, 69, 'Tecido pelas linhas do destino.', 'Mítico', 'Colar'),
('Amuleto da Eternidade', 'Acessorio', 17000, 71, 'Transcende o tempo.', 'Mítico', 'Amuleto'),
('Brinco Primordial', 'Acessorio', 18000, 73, 'Vem da origem do mundo.', 'Mítico', 'Brinco'),
('Anel do Caos', 'Acessorio', 19000, 75, 'Pulsa com energia instável.', 'Mítico', 'Anel'),
('Colar da Ordem', 'Acessorio', 20000, 77, 'Símbolo de equilíbrio absoluto.', 'Mítico', 'Colar'),
('Amuleto Cósmico', 'Acessorio', 21000, 79, 'Contém fragmentos de estrelas.', 'Mítico', 'Amuleto'),
('Anel dos Antigos', 'Acessorio', 25000, 81, 'Relíquia de uma civilização esquecida.', 'Artefato', 'Anel'),
('Colar do Criador', 'Acessorio', 26500, 83, 'Dizem que foi forjado pelo próprio criador.', 'Artefato', 'Colar'),
('Amuleto do Infinito', 'Acessorio', 28000, 85, 'Não tem começo nem fim.', 'Artefato', 'Amuleto'),
('Brinco Divino', 'Acessorio', 29500, 87, 'Concedido por uma entidade divina.', 'Artefato', 'Brinco'),
('Anel do Universo', 'Acessorio', 31000, 89, 'Contém o peso de todo o universo.', 'Artefato', 'Anel'),
('Colar do Apocalipse', 'Acessorio', 32500, 91, 'Presságio do fim dos tempos.', 'Artefato', 'Colar'),
('Amuleto Abissal', 'Acessorio', 34000, 93, 'Vindo das profundezas mais escuras.', 'Artefato', 'Amuleto'),
('Anel de Selune', 'Acessorio', 45000, 95, 'O anel supremo de Selune.', 'Relíquia', 'Anel'),
('Colar de Selune', 'Acessorio', 48000, 97, 'O colar supremo de Selune.', 'Relíquia', 'Colar'),
('Amuleto de Selune', 'Acessorio', 52000, 99, 'O amuleto supremo de Selune.', 'Relíquia', 'Amuleto');

-- ================= ITEM_EFFECTS: ACESSORIOS =================
INSERT INTO item_effects (item_id, attribute_id, valor, percentual) VALUES
((SELECT id FROM items WHERE nome='Anel de Cobre'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 5, FALSE),
((SELECT id FROM items WHERE nome='Colar de Osso'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 5, FALSE),
((SELECT id FROM items WHERE nome='Amuleto de Pedra'), (SELECT id FROM attributes WHERE nome='armadura'), 3, FALSE),
((SELECT id FROM items WHERE nome='Brinco de Latão'), (SELECT id FROM attributes WHERE nome='xp'), 2, TRUE),
((SELECT id FROM items WHERE nome='Anel de Prata Simples'), (SELECT id FROM attributes WHERE nome='ouro'), 2, TRUE),
((SELECT id FROM items WHERE nome='Colar de Couro'), (SELECT id FROM attributes WHERE nome='esquiva'), 2, TRUE),
((SELECT id FROM items WHERE nome='Amuleto do Viajante'), (SELECT id FROM attributes WHERE nome='velocidade'), 3, TRUE),
((SELECT id FROM items WHERE nome='Brinco de Jade'), (SELECT id FROM attributes WHERE nome='mana_por_turno'), 2, FALSE),
((SELECT id FROM items WHERE nome='Anel do Caçador'), (SELECT id FROM attributes WHERE nome='precisao'), 3, TRUE),
((SELECT id FROM items WHERE nome='Colar de Turquesa'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 3, FALSE),
((SELECT id FROM items WHERE nome='Amuleto da Sorte'), (SELECT id FROM attributes WHERE nome='ouro'), 5, TRUE),
((SELECT id FROM items WHERE nome='Brinco de Ônix'), (SELECT id FROM attributes WHERE nome='resistencia_trevas'), 3, FALSE),
((SELECT id FROM items WHERE nome='Anel do Guerreiro'), (SELECT id FROM attributes WHERE nome='ataque'), 5, FALSE),
((SELECT id FROM items WHERE nome='Anel do Guerreiro'), (SELECT id FROM attributes WHERE nome='critico'), 3, TRUE),
((SELECT id FROM items WHERE nome='Colar do Mago'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 15, FALSE),
((SELECT id FROM items WHERE nome='Colar do Mago'), (SELECT id FROM attributes WHERE nome='mana_por_turno'), 3, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Rúnico'), (SELECT id FROM attributes WHERE nome='xp'), 5, TRUE),
((SELECT id FROM items WHERE nome='Amuleto Rúnico'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 10, FALSE),
((SELECT id FROM items WHERE nome='Brinco Élfico'), (SELECT id FROM attributes WHERE nome='precisao'), 5, TRUE),
((SELECT id FROM items WHERE nome='Brinco Élfico'), (SELECT id FROM attributes WHERE nome='esquiva'), 3, TRUE),
((SELECT id FROM items WHERE nome='Anel de Safira'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 6, FALSE),
((SELECT id FROM items WHERE nome='Anel de Safira'), (SELECT id FROM attributes WHERE nome='armadura'), 5, FALSE),
((SELECT id FROM items WHERE nome='Colar de Rubi'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 6, FALSE),
((SELECT id FROM items WHERE nome='Colar de Rubi'), (SELECT id FROM attributes WHERE nome='dano_critico'), 5, TRUE),
((SELECT id FROM items WHERE nome='Amuleto do Vento'), (SELECT id FROM attributes WHERE nome='velocidade'), 5, TRUE),
((SELECT id FROM items WHERE nome='Amuleto do Vento'), (SELECT id FROM attributes WHERE nome='esquiva'), 4, TRUE),
((SELECT id FROM items WHERE nome='Anel do Campeão'), (SELECT id FROM attributes WHERE nome='ataque'), 10, FALSE),
((SELECT id FROM items WHERE nome='Anel do Campeão'), (SELECT id FROM attributes WHERE nome='critico'), 6, TRUE),
((SELECT id FROM items WHERE nome='Colar da Fênix'), (SELECT id FROM attributes WHERE nome='hp_por_turno'), 5, FALSE),
((SELECT id FROM items WHERE nome='Colar da Fênix'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 10, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Sagrado'), (SELECT id FROM attributes WHERE nome='resistencia_luz'), 8, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Sagrado'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 20, FALSE),
((SELECT id FROM items WHERE nome='Brinco Arcano'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 25, FALSE),
((SELECT id FROM items WHERE nome='Brinco Arcano'), (SELECT id FROM attributes WHERE nome='mana_por_turno'), 5, FALSE),
((SELECT id FROM items WHERE nome='Anel da Tempestade'), (SELECT id FROM attributes WHERE nome='resistencia_raio'), 8, FALSE),
((SELECT id FROM items WHERE nome='Anel da Tempestade'), (SELECT id FROM attributes WHERE nome='velocidade'), 6, TRUE),
((SELECT id FROM items WHERE nome='Colar Dracônico'), (SELECT id FROM attributes WHERE nome='dano_critico'), 10, TRUE),
((SELECT id FROM items WHERE nome='Colar Dracônico'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 10, FALSE),
((SELECT id FROM items WHERE nome='Amuleto do Vazio'), (SELECT id FROM attributes WHERE nome='resistencia_trevas'), 10, FALSE),
((SELECT id FROM items WHERE nome='Amuleto do Vazio'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 5, TRUE),
((SELECT id FROM items WHERE nome='Anel do Titã'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 40, FALSE),
((SELECT id FROM items WHERE nome='Anel do Titã'), (SELECT id FROM attributes WHERE nome='armadura'), 10, FALSE),
((SELECT id FROM items WHERE nome='Colar Celestial'), (SELECT id FROM attributes WHERE nome='resistencia_luz'), 15, FALSE),
((SELECT id FROM items WHERE nome='Colar Celestial'), (SELECT id FROM attributes WHERE nome='xp'), 8, TRUE),
((SELECT id FROM items WHERE nome='Amuleto Solar'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 15, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Solar'), (SELECT id FROM attributes WHERE nome='critico'), 8, TRUE),
((SELECT id FROM items WHERE nome='Brinco Lunar'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 15, FALSE),
((SELECT id FROM items WHERE nome='Brinco Lunar'), (SELECT id FROM attributes WHERE nome='esquiva'), 6, TRUE),
((SELECT id FROM items WHERE nome='Anel Glacial'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 18, FALSE),
((SELECT id FROM items WHERE nome='Anel Glacial'), (SELECT id FROM attributes WHERE nome='armadura'), 12, FALSE),
((SELECT id FROM items WHERE nome='Colar Flamejante'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 18, FALSE),
((SELECT id FROM items WHERE nome='Colar Flamejante'), (SELECT id FROM attributes WHERE nome='dano_critico'), 12, TRUE),
((SELECT id FROM items WHERE nome='Amuleto Sombrio'), (SELECT id FROM attributes WHERE nome='resistencia_trevas'), 15, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Sombrio'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 8, TRUE),
((SELECT id FROM items WHERE nome='Anel do Guardião'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 60, FALSE),
((SELECT id FROM items WHERE nome='Anel do Guardião'), (SELECT id FROM attributes WHERE nome='armadura'), 15, FALSE),
((SELECT id FROM items WHERE nome='Anel do Guardião'), (SELECT id FROM attributes WHERE nome='esquiva'), 8, TRUE),
((SELECT id FROM items WHERE nome='Colar do Destino'), (SELECT id FROM attributes WHERE nome='xp'), 12, TRUE),
((SELECT id FROM items WHERE nome='Colar do Destino'), (SELECT id FROM attributes WHERE nome='ouro'), 12, TRUE),
((SELECT id FROM items WHERE nome='Colar do Destino'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 30, FALSE),
((SELECT id FROM items WHERE nome='Amuleto da Eternidade'), (SELECT id FROM attributes WHERE nome='hp_por_turno'), 10, FALSE),
((SELECT id FROM items WHERE nome='Amuleto da Eternidade'), (SELECT id FROM attributes WHERE nome='mana_por_turno'), 8, FALSE),
((SELECT id FROM items WHERE nome='Amuleto da Eternidade'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 30, FALSE),
((SELECT id FROM items WHERE nome='Brinco Primordial'), (SELECT id FROM attributes WHERE nome='critico'), 10, TRUE),
((SELECT id FROM items WHERE nome='Brinco Primordial'), (SELECT id FROM attributes WHERE nome='dano_critico'), 15, TRUE),
((SELECT id FROM items WHERE nome='Brinco Primordial'), (SELECT id FROM attributes WHERE nome='precisao'), 8, TRUE),
((SELECT id FROM items WHERE nome='Anel do Caos'), (SELECT id FROM attributes WHERE nome='resistencia_trevas'), 20, FALSE),
((SELECT id FROM items WHERE nome='Anel do Caos'), (SELECT id FROM attributes WHERE nome='ataque'), 15, FALSE),
((SELECT id FROM items WHERE nome='Anel do Caos'), (SELECT id FROM attributes WHERE nome='velocidade'), 8, TRUE),
((SELECT id FROM items WHERE nome='Colar da Ordem'), (SELECT id FROM attributes WHERE nome='resistencia_luz'), 20, FALSE),
((SELECT id FROM items WHERE nome='Colar da Ordem'), (SELECT id FROM attributes WHERE nome='armadura'), 18, FALSE),
((SELECT id FROM items WHERE nome='Colar da Ordem'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 25, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Cósmico'), (SELECT id FROM attributes WHERE nome='resistencia_raio'), 15, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Cósmico'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 15, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Cósmico'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 15, FALSE),
((SELECT id FROM items WHERE nome='Anel dos Antigos'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 80, FALSE),
((SELECT id FROM items WHERE nome='Anel dos Antigos'), (SELECT id FROM attributes WHERE nome='armadura'), 20, FALSE),
((SELECT id FROM items WHERE nome='Anel dos Antigos'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 10, TRUE),
((SELECT id FROM items WHERE nome='Colar do Criador'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 40, FALSE),
((SELECT id FROM items WHERE nome='Colar do Criador'), (SELECT id FROM attributes WHERE nome='mana_por_turno'), 10, FALSE),
((SELECT id FROM items WHERE nome='Colar do Criador'), (SELECT id FROM attributes WHERE nome='xp'), 15, TRUE),
((SELECT id FROM items WHERE nome='Amuleto do Infinito'), (SELECT id FROM attributes WHERE nome='critico'), 15, TRUE),
((SELECT id FROM items WHERE nome='Amuleto do Infinito'), (SELECT id FROM attributes WHERE nome='dano_critico'), 20, TRUE),
((SELECT id FROM items WHERE nome='Amuleto do Infinito'), (SELECT id FROM attributes WHERE nome='velocidade'), 10, TRUE),
((SELECT id FROM items WHERE nome='Brinco Divino'), (SELECT id FROM attributes WHERE nome='resistencia_luz'), 25, FALSE),
((SELECT id FROM items WHERE nome='Brinco Divino'), (SELECT id FROM attributes WHERE nome='resistencia_trevas'), 25, FALSE),
((SELECT id FROM items WHERE nome='Brinco Divino'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 40, FALSE),
((SELECT id FROM items WHERE nome='Anel do Universo'), (SELECT id FROM attributes WHERE nome='ouro'), 20, TRUE),
((SELECT id FROM items WHERE nome='Anel do Universo'), (SELECT id FROM attributes WHERE nome='xp'), 20, TRUE),
((SELECT id FROM items WHERE nome='Anel do Universo'), (SELECT id FROM attributes WHERE nome='ataque'), 20, FALSE),
((SELECT id FROM items WHERE nome='Colar do Apocalipse'), (SELECT id FROM attributes WHERE nome='resistencia_fogo'), 25, FALSE),
((SELECT id FROM items WHERE nome='Colar do Apocalipse'), (SELECT id FROM attributes WHERE nome='resistencia_gelo'), 25, FALSE),
((SELECT id FROM items WHERE nome='Colar do Apocalipse'), (SELECT id FROM attributes WHERE nome='dano_critico'), 25, TRUE),
((SELECT id FROM items WHERE nome='Amuleto Abissal'), (SELECT id FROM attributes WHERE nome='resistencia_trevas'), 30, FALSE),
((SELECT id FROM items WHERE nome='Amuleto Abissal'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 12, TRUE),
((SELECT id FROM items WHERE nome='Amuleto Abissal'), (SELECT id FROM attributes WHERE nome='armadura'), 25, FALSE),
((SELECT id FROM items WHERE nome='Anel de Selune'), (SELECT id FROM attributes WHERE nome='hp_maximo'), 150, FALSE),
((SELECT id FROM items WHERE nome='Anel de Selune'), (SELECT id FROM attributes WHERE nome='armadura'), 40, FALSE),
((SELECT id FROM items WHERE nome='Anel de Selune'), (SELECT id FROM attributes WHERE nome='critico'), 20, TRUE),
((SELECT id FROM items WHERE nome='Colar de Selune'), (SELECT id FROM attributes WHERE nome='mana_maxima'), 100, FALSE),
((SELECT id FROM items WHERE nome='Colar de Selune'), (SELECT id FROM attributes WHERE nome='mana_por_turno'), 20, FALSE),
((SELECT id FROM items WHERE nome='Colar de Selune'), (SELECT id FROM attributes WHERE nome='xp'), 25, TRUE),
((SELECT id FROM items WHERE nome='Amuleto de Selune'), (SELECT id FROM attributes WHERE nome='resistencia_luz'), 50, FALSE),
((SELECT id FROM items WHERE nome='Amuleto de Selune'), (SELECT id FROM attributes WHERE nome='resistencia_trevas'), 50, FALSE),
((SELECT id FROM items WHERE nome='Amuleto de Selune'), (SELECT id FROM attributes WHERE nome='roubo_vida'), 20, TRUE);
-- ================= LOCATIONS =================
INSERT INTO locations (nome, dificuldade, regiao) VALUES
('Pradaria Inicial', 1, 'Planície'),
('Floresta Sombria', 2, 'Floresta'),
('Colinas Rochosas', 3, 'Montanha'),
('Pântano Nebuloso', 4, 'Pântano'),
('Masmorra Abandonada', 5, 'Masmorra'),
('Deserto Ardente', 6, 'Deserto'),
('Montanhas Geladas', 7, 'Montanha'),
('Caverna de Cristal', 8, 'Caverna'),
('Vulcão Adormecido', 9, 'Vulcão'),
('Ruínas Amaldiçoadas', 10, 'Ruínas');
-- ================= LOOT ITEMS =================
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, funcao, dano, armadura, raridade, subtipo) VALUES
('Pelo de Coelho', 'Loot', 5, 1, 'Pelo macio de coelho selvagem.', NULL, NULL, NULL, 'Comum', NULL),
('Presa de Javali', 'Loot', 12, 3, 'Presa afiada de javali.', NULL, NULL, NULL, 'Comum', NULL),
('Garra de Lobo Filhote', 'Loot', 25, 5, 'Garra pequena mas afiada.', NULL, NULL, NULL, 'Comum', NULL),
('Pelagem de Lobo Sombrio', 'Loot', 30, 6, 'Pelagem escura e densa.', NULL, NULL, NULL, 'Comum', NULL),
('Casca de Urso', 'Loot', 45, 8, 'Pedaço resistente de casca de urso.', NULL, NULL, NULL, 'Comum', NULL),
('Veneno de Aranha', 'Loot', 70, 10, 'Veneno extraído de aranha da floresta.', NULL, NULL, NULL, 'Incomum', NULL),
('Fragmento de Pedra', 'Loot', 90, 11, 'Fragmento de um golem de pedra.', NULL, NULL, NULL, 'Incomum', NULL),
('Pena de Harpia', 'Loot', 120, 13, 'Pena leve e afiada.', NULL, NULL, NULL, 'Incomum', NULL),
('Presa de Orc', 'Loot', 160, 15, 'Presa grande de um orc guerreiro.', NULL, NULL, NULL, 'Incomum', NULL),
('Muco de Sapo', 'Loot', 190, 16, 'Muco viscoso de sapo gigante.', NULL, NULL, NULL, 'Incomum', NULL),
('Bandagem de Múmia', 'Loot', 230, 18, 'Bandagem antiga e amaldiçoada.', NULL, NULL, NULL, 'Incomum', NULL),
('Escama de Crocodilo', 'Loot', 280, 20, 'Escama resistente de crocodilo gigante.', NULL, NULL, NULL, 'Raro', NULL),
('Osso de Esqueleto', 'Loot', 320, 21, 'Osso desgastado de um morto-vivo.', NULL, NULL, NULL, 'Raro', NULL),
('Carne Podre de Zumbi', 'Loot', 360, 24, 'Carne em decomposição, ainda útil pra alquimia.', NULL, NULL, NULL, 'Raro', NULL),
('Fragmento de Armadura Caída', 'Loot', 450, 30, 'Resto de armadura de um cavaleiro caído.', NULL, NULL, NULL, 'Raro', NULL),
('Casca de Escorpião', 'Loot', 520, 31, 'Casca dura de escorpião do deserto.', NULL, NULL, NULL, 'Raro', NULL),
('Areia Amaldiçoada', 'Loot', 600, 35, 'Areia impregnada de magia sombria.', NULL, NULL, NULL, 'Raro', NULL),
('Essência de Djinn', 'Loot', 750, 40, 'Essência mágica capturada de um djinn.', NULL, NULL, NULL, 'Épico', NULL),
('Pelo Glacial', 'Loot', 900, 41, 'Pelo que nunca derrete.', NULL, NULL, NULL, 'Épico', NULL),
('Presa de Troll', 'Loot', 1050, 45, 'Presa robusta de troll das neves.', NULL, NULL, NULL, 'Épico', NULL),
('Núcleo de Gelo', 'Loot', 1300, 50, 'Núcleo mágico eternamente congelado.', NULL, NULL, NULL, 'Épico', NULL),
('Fragmento de Cristal', 'Loot', 1600, 51, 'Fragmento brilhante de cristal mágico.', NULL, NULL, NULL, 'Épico', NULL),
('Asa de Morcego Gigante', 'Loot', 1900, 58, 'Asa membranosa de grande envergadura.', NULL, NULL, NULL, 'Lendário', NULL),
('Olho de Basilisco', 'Loot', 2500, 65, 'Olho que ainda pulsa com magia petrificante.', NULL, NULL, NULL, 'Lendário', NULL),
('Cinzas Vulcânicas', 'Loot', 3000, 66, 'Cinzas quentes de origem vulcânica.', NULL, NULL, NULL, 'Lendário', NULL),
('Escama de Salamandra', 'Loot', 3600, 73, 'Escama resistente ao fogo.', NULL, NULL, NULL, 'Lendário', NULL),
('Pena de Fênix', 'Loot', 4500, 80, 'Pena que ainda emite calor próprio.', NULL, NULL, NULL, 'Mítico', NULL),
('Pó de Lich', 'Loot', 5500, 81, 'Resíduo de energia necromântica.', NULL, NULL, NULL, 'Mítico', NULL),
('Elmo de Cavaleiro da Morte', 'Loot', 6500, 90, 'Elmo enegrecido de um cavaleiro amaldiçoado.', NULL, NULL, NULL, 'Mítico', NULL),
('Escama de Dragão Ancião', 'Loot', 9000, 100, 'Escama de um dos dragões mais antigos do mundo.', NULL, NULL, NULL, 'Artefato', NULL);

-- ===== LOOT DE CRAFTING: COMUM =====
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, funcao, dano, armadura, raridade, subtipo) VALUES
('Minério de Cobre', 'Loot', 15, 1, 'Pedaço bruto de cobre, extraído de veios rasos.', NULL, NULL, NULL, 'Comum', 'Material'),
('Minério de Estanho', 'Loot', 18, 2, 'Minério leve, usado junto ao cobre para ligas antigas.', NULL, NULL, NULL, 'Comum', 'Material'),
('Madeira de Carvalho', 'Loot', 21, 2, 'Tora resistente de carvalho, boa para cabos e hastes.', NULL, NULL, NULL, 'Comum', 'Material'),
('Couro Curado', 'Loot', 24, 3, 'Couro tratado, pronto para costura em armaduras leves.', NULL, NULL, NULL, 'Comum', 'Material'),
('Barbante', 'Loot', 27, 3, 'Fio resistente, usado para amarrar pingentes e enfeites.', NULL, NULL, NULL, 'Comum', 'Material'),
('Pedra Comum', 'Loot', 30, 4, 'Pedra polida sem propriedades mágicas aparentes.', NULL, NULL, NULL, 'Comum', 'Material'),
('Bronze', 'Loot', 33, 5, 'Liga metálica de cobre e estanho, já fundida.', NULL, NULL, NULL, 'Comum', 'Material'),
('Linha de Seda', 'Loot', 36, 5, 'Fio fino e forte, tecido a partir de casulos selecionados.', NULL, NULL, NULL, 'Comum', 'Material'),
('Erva Medicinal', 'Loot', 39, 6, 'Planta comum com propriedades curativas leves.', NULL, NULL, NULL, 'Comum', 'Material'),
('Água Pura', 'Loot', 42, 6, 'Água filtrada de nascente, base para poções simples.', NULL, NULL, NULL, 'Comum', 'Material'),
('Frasco', 'Loot', 45, 7, 'Frasco de vidro para engarrafar poções.', NULL, NULL, NULL, 'Comum', 'Material'),
('Frasco Vazio', 'Loot', 48, 8, 'Frasco limpo, ainda sem conteúdo.', NULL, NULL, NULL, 'Comum', 'Material'),
('Flor Solar', 'Loot', 51, 8, 'Flor amarela que se abre ao nascer do sol.', NULL, NULL, NULL, 'Comum', 'Material'),
('Casca de Árvore', 'Loot', 54, 9, 'Casca resistente, usada em preparos revigorantes.', NULL, NULL, NULL, 'Comum', 'Material'),
('Trevo Dourado', 'Loot', 57, 9, 'Trevo raro de tom dourado, dizem que traz sorte.', NULL, NULL, NULL, 'Comum', 'Material'),
('Hortelã Selvagem', 'Loot', 60, 10, 'Erva aromática que cresce livremente em campos abertos.', NULL, NULL, NULL, 'Comum', 'Material');

-- ===== LOOT DE CRAFTING: INCOMUM =====
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, funcao, dano, armadura, raridade, subtipo) VALUES
('Minério de Ferro', 'Loot', 70, 10, 'Minério pesado, base de quase todo equipamento militar.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Madeira Negra', 'Loot', 83, 11, 'Madeira escurecida e mais densa que a comum.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Corrente', 'Loot', 97, 12, 'Elos de metal forjados para cotas de malha.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Resina', 'Loot', 110, 12, 'Seiva endurecida, usada para reforçar couro.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Musgo Ancião', 'Loot', 123, 13, 'Musgo que cresce há décadas sobre pedras antigas.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Erva Revigorante', 'Loot', 137, 14, 'Planta que acelera a recuperação do corpo.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Mel Silvestre', 'Loot', 150, 15, 'Mel colhido de colmeias selvagens, muito energético.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Muco Pegajoso', 'Loot', 163, 16, 'Secreção viscosa usada como base de venenos.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Óleo Vegetal', 'Loot', 177, 17, 'Óleo extraído de sementes, base para óleos de arma.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Pergaminho', 'Loot', 190, 18, 'Pergaminho em branco, pronto para ser encantado.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Pergaminho Antigo', 'Loot', 203, 18, 'Pergaminho desgastado com traços de magia residual.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Runa Quebrada', 'Loot', 217, 19, 'Fragmento de uma runa maior, ainda pulsando fracamente.', NULL, NULL, NULL, 'Incomum', 'Material'),
('Quartzo', 'Loot', 230, 20, 'Cristal comum, usado como base para encantamentos simples.', NULL, NULL, NULL, 'Incomum', 'Material');

-- ===== LOOT DE CRAFTING: RARO =====
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, funcao, dano, armadura, raridade, subtipo) VALUES
('Minério de Aço', 'Loot', 280, 20, 'Minério já tratado, pronto para forja de aço.', NULL, NULL, NULL, 'Raro', 'Material'),
('Carvão Mineral', 'Loot', 303, 21, 'Combustível denso, essencial para fornalhas de forja.', NULL, NULL, NULL, 'Raro', 'Material'),
('Prata', 'Loot', 326, 22, 'Metal nobre, eficaz contra criaturas amaldiçoadas.', NULL, NULL, NULL, 'Raro', 'Material'),
('Safira', 'Loot', 349, 23, 'Pedra azul de corte lapidado, associada ao gelo.', NULL, NULL, NULL, 'Raro', 'Material'),
('Esmeralda', 'Loot', 372, 24, 'Pedra verde vibrante, associada à natureza.', NULL, NULL, NULL, 'Raro', 'Material'),
('Rubi', 'Loot', 396, 25, 'Pedra vermelha intensa, associada ao fogo.', NULL, NULL, NULL, 'Raro', 'Material'),
('Ônix', 'Loot', 419, 26, 'Pedra negra opaca, associada às trevas.', NULL, NULL, NULL, 'Raro', 'Material'),
('Quartzo Arcano', 'Loot', 442, 27, 'Cristal imbuído de energia mágica latente.', NULL, NULL, NULL, 'Raro', 'Material'),
('Pó Arcano', 'Loot', 465, 28, 'Pó fino que emite um brilho azulado tênue.', NULL, NULL, NULL, 'Raro', 'Material'),
('Flor Lunar', 'Loot', 488, 28, 'Flor que só desabrocha sob a luz da lua.', NULL, NULL, NULL, 'Raro', 'Material'),
('Flor de Sangue', 'Loot', 511, 29, 'Flor vermelho-escura, associada à vitalidade.', NULL, NULL, NULL, 'Raro', 'Material'),
('Essência Vital', 'Loot', 534, 30, 'Essência concentrada de força vital.', NULL, NULL, NULL, 'Raro', 'Material'),
('Fruta Rubra', 'Loot', 558, 31, 'Fruta rara que fortalece quem a consome.', NULL, NULL, NULL, 'Raro', 'Material'),
('Cristal Azul', 'Loot', 581, 32, 'Cristal translúcido usado em encantamentos protetores.', NULL, NULL, NULL, 'Raro', 'Material'),
('Pedra da Lua', 'Loot', 604, 33, 'Pedra pálida que armazena energia lunar.', NULL, NULL, NULL, 'Raro', 'Material'),
('Lírio Azul', 'Loot', 627, 34, 'Flor sagrada usada em rituais de purificação.', NULL, NULL, NULL, 'Raro', 'Material'),
('Runa Completa', 'Loot', 650, 35, 'Runa reconstituída a partir de três fragmentos.', NULL, NULL, NULL, 'Raro', 'Material');

-- ===== LOOT DE CRAFTING: ÉPICO =====
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, funcao, dano, armadura, raridade, subtipo) VALUES
('Mithril', 'Loot', 750, 40, 'Metal raro e leve, mais forte que qualquer aço.', NULL, NULL, NULL, 'Épico', 'Material'),
('Água Benta', 'Loot', 892, 42, 'Água abençoada por um clérigo, usada em rituais sagrados.', NULL, NULL, NULL, 'Épico', 'Material'),
('Fragmento Espiritual', 'Loot', 1033, 45, 'Fragmento de energia espiritual condensada.', NULL, NULL, NULL, 'Épico', 'Material'),
('Núcleo Mágico', 'Loot', 1175, 48, 'Núcleo cristalizado de pura energia arcana.', NULL, NULL, NULL, 'Épico', 'Material'),
('Diamante Bruto', 'Loot', 1317, 50, 'Diamante ainda não lapidado, denso em energia.', NULL, NULL, NULL, 'Épico', 'Material'),
('Essência Flamejante', 'Loot', 1458, 52, 'Essência que arde sem se consumir.', NULL, NULL, NULL, 'Épico', 'Material'),
('Essência Gélida', 'Loot', 1600, 55, 'Essência que nunca perde seu frio glacial.', NULL, NULL, NULL, 'Épico', 'Material');

-- ===== LOOT DE CRAFTING: LENDÁRIO =====
INSERT INTO items (nome, tipo, valor, nivel_requerido, descricao, funcao, dano, armadura, raridade, subtipo) VALUES
('Adamantita', 'Loot', 1900, 58, 'Metal quase indestrutível, forjado sob pressões extremas.', NULL, NULL, NULL, 'Lendário', 'Material'),
('Escama de Dragão', 'Loot', 2325, 62, 'Escama resistente de um dragão jovem.', NULL, NULL, NULL, 'Lendário', 'Material'),
('Diamante', 'Loot', 2750, 66, 'Diamante lapidado, símbolo de poder e riqueza.', NULL, NULL, NULL, 'Lendário', 'Material'),
('Essência Celestial', 'Loot', 3175, 69, 'Essência pura vinda de planos superiores.', NULL, NULL, NULL, 'Lendário', 'Material'),
('Essência Sombria', 'Loot', 3600, 73, 'Essência corrompida por trevas antigas.', NULL, NULL, NULL, 'Lendário', 'Material');

-- ================= MONSTERS =================
INSERT INTO monsters (nome, hp, ataque, xp, ouro) VALUES
('Coelho Selvagem', 15, 3, 5, 2),
('Javali Selvagem', 25, 5, 8, 4),
('Lobo Filhote', 30, 6, 10, 5),
('Bandido Novato', 35, 7, 12, 8),
('Aranha Gigante Pequena', 45, 9, 18, 12),
('Lobo Sombrio', 60, 12, 25, 15),
('Urso Pardo', 80, 15, 32, 20),
('Aranha Venenosa', 70, 14, 30, 18),
('Duende Travesso', 65, 13, 28, 22),
('Bandido Florestal', 90, 18, 40, 30),
('Golem de Pedra Pequeno', 150, 20, 55, 40),
('Harpia', 120, 24, 60, 45),
('Orc Guerreiro', 160, 28, 70, 55),
('Gnoll Caçador', 140, 26, 65, 50),
('Águia Gigante', 130, 22, 58, 42),
('Sapo Gigante', 200, 30, 90, 70),
('Múmia Menor', 230, 34, 100, 80),
('Vermeling Lodoso', 180, 28, 85, 65),
('Bruxa do Pântano', 210, 38, 110, 90),
('Crocodilo Gigante', 260, 40, 120, 100),
('Esqueleto Guerreiro', 300, 45, 150, 120),
('Zumbi', 350, 40, 140, 110),
('Rato Gigante', 250, 35, 120, 90),
('Aranha Negra', 320, 50, 160, 130),
('Cavaleiro Caído', 420, 60, 220, 180),
('Escorpião Gigante', 480, 65, 260, 220),
('Múmia Real', 550, 70, 300, 260),
('Djinn Menor', 500, 75, 310, 280),
('Serpente de Areia', 460, 68, 280, 240),
('Ladrão do Deserto', 430, 60, 250, 300),
('Lobo Glacial', 650, 85, 380, 320),
('Troll das Neves', 800, 95, 450, 380),
('Elemental de Gelo', 750, 100, 470, 400),
('Yeti', 900, 110, 520, 450),
('Harpia Congelante', 700, 90, 420, 360),
('Golem de Cristal', 1200, 130, 650, 550),
('Morcego Gigante', 950, 115, 560, 480),
('Aranha Cristalina', 1100, 125, 620, 520),
('Anão Renegado', 1300, 140, 700, 600),
('Basilisco', 1500, 160, 850, 750),
('Elemental de Fogo', 1800, 180, 1000, 900),
('Salamandra Gigante', 1700, 175, 950, 850),
('Demônio Menor', 2000, 200, 1150, 1050),
('Golem de Magma', 2200, 210, 1250, 1150),
('Fênix Selvagem', 2500, 230, 1450, 1350),
('Lich', 3000, 260, 1800, 1700),
('Cavaleiro da Morte', 3300, 280, 2000, 1900),
('Dragão Ancião', 4500, 350, 3000, 2900),
('Demônio Maior', 3800, 300, 2400, 2300),
('Guardião Ancestral', 5000, 380, 3500, 3400);

-- ================= MONSTER_LOCATIONS =================
INSERT INTO monster_locations (monster_id, location_id) VALUES
((SELECT id FROM monsters WHERE nome='Coelho Selvagem'), (SELECT id FROM locations WHERE nome='Pradaria Inicial')),
((SELECT id FROM monsters WHERE nome='Javali Selvagem'), (SELECT id FROM locations WHERE nome='Pradaria Inicial')),
((SELECT id FROM monsters WHERE nome='Lobo Filhote'), (SELECT id FROM locations WHERE nome='Pradaria Inicial')),
((SELECT id FROM monsters WHERE nome='Bandido Novato'), (SELECT id FROM locations WHERE nome='Pradaria Inicial')),
((SELECT id FROM monsters WHERE nome='Aranha Gigante Pequena'), (SELECT id FROM locations WHERE nome='Pradaria Inicial')),
((SELECT id FROM monsters WHERE nome='Lobo Sombrio'), (SELECT id FROM locations WHERE nome='Floresta Sombria')),
((SELECT id FROM monsters WHERE nome='Urso Pardo'), (SELECT id FROM locations WHERE nome='Floresta Sombria')),
((SELECT id FROM monsters WHERE nome='Aranha Venenosa'), (SELECT id FROM locations WHERE nome='Floresta Sombria')),
((SELECT id FROM monsters WHERE nome='Duende Travesso'), (SELECT id FROM locations WHERE nome='Floresta Sombria')),
((SELECT id FROM monsters WHERE nome='Bandido Florestal'), (SELECT id FROM locations WHERE nome='Floresta Sombria')),
((SELECT id FROM monsters WHERE nome='Golem de Pedra Pequeno'), (SELECT id FROM locations WHERE nome='Colinas Rochosas')),
((SELECT id FROM monsters WHERE nome='Harpia'), (SELECT id FROM locations WHERE nome='Colinas Rochosas')),
((SELECT id FROM monsters WHERE nome='Orc Guerreiro'), (SELECT id FROM locations WHERE nome='Colinas Rochosas')),
((SELECT id FROM monsters WHERE nome='Gnoll Caçador'), (SELECT id FROM locations WHERE nome='Colinas Rochosas')),
((SELECT id FROM monsters WHERE nome='Águia Gigante'), (SELECT id FROM locations WHERE nome='Colinas Rochosas')),
((SELECT id FROM monsters WHERE nome='Sapo Gigante'), (SELECT id FROM locations WHERE nome='Pântano Nebuloso')),
((SELECT id FROM monsters WHERE nome='Múmia Menor'), (SELECT id FROM locations WHERE nome='Pântano Nebuloso')),
((SELECT id FROM monsters WHERE nome='Vermeling Lodoso'), (SELECT id FROM locations WHERE nome='Pântano Nebuloso')),
((SELECT id FROM monsters WHERE nome='Bruxa do Pântano'), (SELECT id FROM locations WHERE nome='Pântano Nebuloso')),
((SELECT id FROM monsters WHERE nome='Crocodilo Gigante'), (SELECT id FROM locations WHERE nome='Pântano Nebuloso')),
((SELECT id FROM monsters WHERE nome='Esqueleto Guerreiro'), (SELECT id FROM locations WHERE nome='Masmorra Abandonada')),
((SELECT id FROM monsters WHERE nome='Zumbi'), (SELECT id FROM locations WHERE nome='Masmorra Abandonada')),
((SELECT id FROM monsters WHERE nome='Rato Gigante'), (SELECT id FROM locations WHERE nome='Masmorra Abandonada')),
((SELECT id FROM monsters WHERE nome='Aranha Negra'), (SELECT id FROM locations WHERE nome='Masmorra Abandonada')),
((SELECT id FROM monsters WHERE nome='Cavaleiro Caído'), (SELECT id FROM locations WHERE nome='Masmorra Abandonada')),
((SELECT id FROM monsters WHERE nome='Escorpião Gigante'), (SELECT id FROM locations WHERE nome='Deserto Ardente')),
((SELECT id FROM monsters WHERE nome='Múmia Real'), (SELECT id FROM locations WHERE nome='Deserto Ardente')),
((SELECT id FROM monsters WHERE nome='Djinn Menor'), (SELECT id FROM locations WHERE nome='Deserto Ardente')),
((SELECT id FROM monsters WHERE nome='Serpente de Areia'), (SELECT id FROM locations WHERE nome='Deserto Ardente')),
((SELECT id FROM monsters WHERE nome='Ladrão do Deserto'), (SELECT id FROM locations WHERE nome='Deserto Ardente')),
((SELECT id FROM monsters WHERE nome='Lobo Glacial'), (SELECT id FROM locations WHERE nome='Montanhas Geladas')),
((SELECT id FROM monsters WHERE nome='Troll das Neves'), (SELECT id FROM locations WHERE nome='Montanhas Geladas')),
((SELECT id FROM monsters WHERE nome='Elemental de Gelo'), (SELECT id FROM locations WHERE nome='Montanhas Geladas')),
((SELECT id FROM monsters WHERE nome='Yeti'), (SELECT id FROM locations WHERE nome='Montanhas Geladas')),
((SELECT id FROM monsters WHERE nome='Harpia Congelante'), (SELECT id FROM locations WHERE nome='Montanhas Geladas')),
((SELECT id FROM monsters WHERE nome='Golem de Cristal'), (SELECT id FROM locations WHERE nome='Caverna de Cristal')),
((SELECT id FROM monsters WHERE nome='Morcego Gigante'), (SELECT id FROM locations WHERE nome='Caverna de Cristal')),
((SELECT id FROM monsters WHERE nome='Aranha Cristalina'), (SELECT id FROM locations WHERE nome='Caverna de Cristal')),
((SELECT id FROM monsters WHERE nome='Anão Renegado'), (SELECT id FROM locations WHERE nome='Caverna de Cristal')),
((SELECT id FROM monsters WHERE nome='Basilisco'), (SELECT id FROM locations WHERE nome='Caverna de Cristal')),
((SELECT id FROM monsters WHERE nome='Elemental de Fogo'), (SELECT id FROM locations WHERE nome='Vulcão Adormecido')),
((SELECT id FROM monsters WHERE nome='Salamandra Gigante'), (SELECT id FROM locations WHERE nome='Vulcão Adormecido')),
((SELECT id FROM monsters WHERE nome='Demônio Menor'), (SELECT id FROM locations WHERE nome='Vulcão Adormecido')),
((SELECT id FROM monsters WHERE nome='Golem de Magma'), (SELECT id FROM locations WHERE nome='Vulcão Adormecido')),
((SELECT id FROM monsters WHERE nome='Fênix Selvagem'), (SELECT id FROM locations WHERE nome='Vulcão Adormecido')),
((SELECT id FROM monsters WHERE nome='Lich'), (SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas')),
((SELECT id FROM monsters WHERE nome='Cavaleiro da Morte'), (SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas')),
((SELECT id FROM monsters WHERE nome='Dragão Ancião'), (SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas')),
((SELECT id FROM monsters WHERE nome='Demônio Maior'), (SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas')),
((SELECT id FROM monsters WHERE nome='Guardião Ancestral'), (SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'));

-- ================= MONSTER_DROPS =================
INSERT INTO monster_drops (monster_id, item_id, chance_drop) VALUES
((SELECT id FROM monsters WHERE nome='Coelho Selvagem'), (SELECT id FROM items WHERE nome='Pelo de Coelho'), 55.00),
((SELECT id FROM monsters WHERE nome='Coelho Selvagem'), (SELECT id FROM items WHERE nome='Presa de Javali'), 25.00),
((SELECT id FROM monsters WHERE nome='Javali Selvagem'), (SELECT id FROM items WHERE nome='Pelo de Coelho'), 55.00),
((SELECT id FROM monsters WHERE nome='Javali Selvagem'), (SELECT id FROM items WHERE nome='Presa de Javali'), 25.00),
((SELECT id FROM monsters WHERE nome='Lobo Filhote'), (SELECT id FROM items WHERE nome='Pelo de Coelho'), 55.00),
((SELECT id FROM monsters WHERE nome='Lobo Filhote'), (SELECT id FROM items WHERE nome='Presa de Javali'), 25.00),
((SELECT id FROM monsters WHERE nome='Bandido Novato'), (SELECT id FROM items WHERE nome='Pelo de Coelho'), 55.00),
((SELECT id FROM monsters WHERE nome='Bandido Novato'), (SELECT id FROM items WHERE nome='Presa de Javali'), 25.00),
((SELECT id FROM monsters WHERE nome='Aranha Gigante Pequena'), (SELECT id FROM items WHERE nome='Pelo de Coelho'), 55.00),
((SELECT id FROM monsters WHERE nome='Aranha Gigante Pequena'), (SELECT id FROM items WHERE nome='Presa de Javali'), 25.00),
((SELECT id FROM monsters WHERE nome='Aranha Gigante Pequena'), (SELECT id FROM items WHERE nome='Garra de Lobo Filhote'), 8.00),
((SELECT id FROM monsters WHERE nome='Lobo Sombrio'), (SELECT id FROM items WHERE nome='Pelagem de Lobo Sombrio'), 55.00),
((SELECT id FROM monsters WHERE nome='Lobo Sombrio'), (SELECT id FROM items WHERE nome='Casca de Urso'), 25.00),
((SELECT id FROM monsters WHERE nome='Urso Pardo'), (SELECT id FROM items WHERE nome='Pelagem de Lobo Sombrio'), 55.00),
((SELECT id FROM monsters WHERE nome='Urso Pardo'), (SELECT id FROM items WHERE nome='Casca de Urso'), 25.00),
((SELECT id FROM monsters WHERE nome='Aranha Venenosa'), (SELECT id FROM items WHERE nome='Pelagem de Lobo Sombrio'), 55.00),
((SELECT id FROM monsters WHERE nome='Aranha Venenosa'), (SELECT id FROM items WHERE nome='Casca de Urso'), 25.00),
((SELECT id FROM monsters WHERE nome='Duende Travesso'), (SELECT id FROM items WHERE nome='Pelagem de Lobo Sombrio'), 55.00),
((SELECT id FROM monsters WHERE nome='Duende Travesso'), (SELECT id FROM items WHERE nome='Casca de Urso'), 25.00),
((SELECT id FROM monsters WHERE nome='Bandido Florestal'), (SELECT id FROM items WHERE nome='Pelagem de Lobo Sombrio'), 55.00),
((SELECT id FROM monsters WHERE nome='Bandido Florestal'), (SELECT id FROM items WHERE nome='Casca de Urso'), 25.00),
((SELECT id FROM monsters WHERE nome='Bandido Florestal'), (SELECT id FROM items WHERE nome='Veneno de Aranha'), 8.00),
((SELECT id FROM monsters WHERE nome='Golem de Pedra Pequeno'), (SELECT id FROM items WHERE nome='Fragmento de Pedra'), 55.00),
((SELECT id FROM monsters WHERE nome='Golem de Pedra Pequeno'), (SELECT id FROM items WHERE nome='Pena de Harpia'), 25.00),
((SELECT id FROM monsters WHERE nome='Harpia'), (SELECT id FROM items WHERE nome='Fragmento de Pedra'), 55.00),
((SELECT id FROM monsters WHERE nome='Harpia'), (SELECT id FROM items WHERE nome='Pena de Harpia'), 25.00),
((SELECT id FROM monsters WHERE nome='Orc Guerreiro'), (SELECT id FROM items WHERE nome='Fragmento de Pedra'), 55.00),
((SELECT id FROM monsters WHERE nome='Orc Guerreiro'), (SELECT id FROM items WHERE nome='Pena de Harpia'), 25.00),
((SELECT id FROM monsters WHERE nome='Gnoll Caçador'), (SELECT id FROM items WHERE nome='Fragmento de Pedra'), 55.00),
((SELECT id FROM monsters WHERE nome='Gnoll Caçador'), (SELECT id FROM items WHERE nome='Pena de Harpia'), 25.00),
((SELECT id FROM monsters WHERE nome='Águia Gigante'), (SELECT id FROM items WHERE nome='Fragmento de Pedra'), 55.00),
((SELECT id FROM monsters WHERE nome='Águia Gigante'), (SELECT id FROM items WHERE nome='Pena de Harpia'), 25.00),
((SELECT id FROM monsters WHERE nome='Águia Gigante'), (SELECT id FROM items WHERE nome='Presa de Orc'), 8.00),
((SELECT id FROM monsters WHERE nome='Sapo Gigante'), (SELECT id FROM items WHERE nome='Muco de Sapo'), 55.00),
((SELECT id FROM monsters WHERE nome='Sapo Gigante'), (SELECT id FROM items WHERE nome='Bandagem de Múmia'), 25.00),
((SELECT id FROM monsters WHERE nome='Múmia Menor'), (SELECT id FROM items WHERE nome='Muco de Sapo'), 55.00),
((SELECT id FROM monsters WHERE nome='Múmia Menor'), (SELECT id FROM items WHERE nome='Bandagem de Múmia'), 25.00),
((SELECT id FROM monsters WHERE nome='Vermeling Lodoso'), (SELECT id FROM items WHERE nome='Muco de Sapo'), 55.00),
((SELECT id FROM monsters WHERE nome='Vermeling Lodoso'), (SELECT id FROM items WHERE nome='Bandagem de Múmia'), 25.00),
((SELECT id FROM monsters WHERE nome='Bruxa do Pântano'), (SELECT id FROM items WHERE nome='Muco de Sapo'), 55.00),
((SELECT id FROM monsters WHERE nome='Bruxa do Pântano'), (SELECT id FROM items WHERE nome='Bandagem de Múmia'), 25.00),
((SELECT id FROM monsters WHERE nome='Crocodilo Gigante'), (SELECT id FROM items WHERE nome='Muco de Sapo'), 55.00),
((SELECT id FROM monsters WHERE nome='Crocodilo Gigante'), (SELECT id FROM items WHERE nome='Bandagem de Múmia'), 25.00),
((SELECT id FROM monsters WHERE nome='Crocodilo Gigante'), (SELECT id FROM items WHERE nome='Escama de Crocodilo'), 8.00),
((SELECT id FROM monsters WHERE nome='Esqueleto Guerreiro'), (SELECT id FROM items WHERE nome='Osso de Esqueleto'), 55.00),
((SELECT id FROM monsters WHERE nome='Esqueleto Guerreiro'), (SELECT id FROM items WHERE nome='Carne Podre de Zumbi'), 25.00),
((SELECT id FROM monsters WHERE nome='Zumbi'), (SELECT id FROM items WHERE nome='Osso de Esqueleto'), 55.00),
((SELECT id FROM monsters WHERE nome='Zumbi'), (SELECT id FROM items WHERE nome='Carne Podre de Zumbi'), 25.00),
((SELECT id FROM monsters WHERE nome='Rato Gigante'), (SELECT id FROM items WHERE nome='Osso de Esqueleto'), 55.00),
((SELECT id FROM monsters WHERE nome='Rato Gigante'), (SELECT id FROM items WHERE nome='Carne Podre de Zumbi'), 25.00),
((SELECT id FROM monsters WHERE nome='Aranha Negra'), (SELECT id FROM items WHERE nome='Osso de Esqueleto'), 55.00),
((SELECT id FROM monsters WHERE nome='Aranha Negra'), (SELECT id FROM items WHERE nome='Carne Podre de Zumbi'), 25.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro Caído'), (SELECT id FROM items WHERE nome='Osso de Esqueleto'), 55.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro Caído'), (SELECT id FROM items WHERE nome='Carne Podre de Zumbi'), 25.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro Caído'), (SELECT id FROM items WHERE nome='Fragmento de Armadura Caída'), 8.00),
((SELECT id FROM monsters WHERE nome='Escorpião Gigante'), (SELECT id FROM items WHERE nome='Casca de Escorpião'), 55.00),
((SELECT id FROM monsters WHERE nome='Escorpião Gigante'), (SELECT id FROM items WHERE nome='Areia Amaldiçoada'), 25.00),
((SELECT id FROM monsters WHERE nome='Múmia Real'), (SELECT id FROM items WHERE nome='Casca de Escorpião'), 55.00),
((SELECT id FROM monsters WHERE nome='Múmia Real'), (SELECT id FROM items WHERE nome='Areia Amaldiçoada'), 25.00),
((SELECT id FROM monsters WHERE nome='Djinn Menor'), (SELECT id FROM items WHERE nome='Casca de Escorpião'), 55.00),
((SELECT id FROM monsters WHERE nome='Djinn Menor'), (SELECT id FROM items WHERE nome='Areia Amaldiçoada'), 25.00),
((SELECT id FROM monsters WHERE nome='Serpente de Areia'), (SELECT id FROM items WHERE nome='Casca de Escorpião'), 55.00),
((SELECT id FROM monsters WHERE nome='Serpente de Areia'), (SELECT id FROM items WHERE nome='Areia Amaldiçoada'), 25.00),
((SELECT id FROM monsters WHERE nome='Ladrão do Deserto'), (SELECT id FROM items WHERE nome='Casca de Escorpião'), 55.00),
((SELECT id FROM monsters WHERE nome='Ladrão do Deserto'), (SELECT id FROM items WHERE nome='Areia Amaldiçoada'), 25.00),
((SELECT id FROM monsters WHERE nome='Ladrão do Deserto'), (SELECT id FROM items WHERE nome='Essência de Djinn'), 8.00),
((SELECT id FROM monsters WHERE nome='Lobo Glacial'), (SELECT id FROM items WHERE nome='Pelo Glacial'), 55.00),
((SELECT id FROM monsters WHERE nome='Lobo Glacial'), (SELECT id FROM items WHERE nome='Presa de Troll'), 25.00),
((SELECT id FROM monsters WHERE nome='Troll das Neves'), (SELECT id FROM items WHERE nome='Pelo Glacial'), 55.00),
((SELECT id FROM monsters WHERE nome='Troll das Neves'), (SELECT id FROM items WHERE nome='Presa de Troll'), 25.00),
((SELECT id FROM monsters WHERE nome='Elemental de Gelo'), (SELECT id FROM items WHERE nome='Pelo Glacial'), 55.00),
((SELECT id FROM monsters WHERE nome='Elemental de Gelo'), (SELECT id FROM items WHERE nome='Presa de Troll'), 25.00),
((SELECT id FROM monsters WHERE nome='Yeti'), (SELECT id FROM items WHERE nome='Pelo Glacial'), 55.00),
((SELECT id FROM monsters WHERE nome='Yeti'), (SELECT id FROM items WHERE nome='Presa de Troll'), 25.00),
((SELECT id FROM monsters WHERE nome='Harpia Congelante'), (SELECT id FROM items WHERE nome='Pelo Glacial'), 55.00),
((SELECT id FROM monsters WHERE nome='Harpia Congelante'), (SELECT id FROM items WHERE nome='Presa de Troll'), 25.00),
((SELECT id FROM monsters WHERE nome='Harpia Congelante'), (SELECT id FROM items WHERE nome='Núcleo de Gelo'), 8.00),
((SELECT id FROM monsters WHERE nome='Golem de Cristal'), (SELECT id FROM items WHERE nome='Fragmento de Cristal'), 55.00),
((SELECT id FROM monsters WHERE nome='Golem de Cristal'), (SELECT id FROM items WHERE nome='Asa de Morcego Gigante'), 25.00),
((SELECT id FROM monsters WHERE nome='Morcego Gigante'), (SELECT id FROM items WHERE nome='Fragmento de Cristal'), 55.00),
((SELECT id FROM monsters WHERE nome='Morcego Gigante'), (SELECT id FROM items WHERE nome='Asa de Morcego Gigante'), 25.00),
((SELECT id FROM monsters WHERE nome='Aranha Cristalina'), (SELECT id FROM items WHERE nome='Fragmento de Cristal'), 55.00),
((SELECT id FROM monsters WHERE nome='Aranha Cristalina'), (SELECT id FROM items WHERE nome='Asa de Morcego Gigante'), 25.00),
((SELECT id FROM monsters WHERE nome='Anão Renegado'), (SELECT id FROM items WHERE nome='Fragmento de Cristal'), 55.00),
((SELECT id FROM monsters WHERE nome='Anão Renegado'), (SELECT id FROM items WHERE nome='Asa de Morcego Gigante'), 25.00),
((SELECT id FROM monsters WHERE nome='Basilisco'), (SELECT id FROM items WHERE nome='Fragmento de Cristal'), 55.00),
((SELECT id FROM monsters WHERE nome='Basilisco'), (SELECT id FROM items WHERE nome='Asa de Morcego Gigante'), 25.00),
((SELECT id FROM monsters WHERE nome='Basilisco'), (SELECT id FROM items WHERE nome='Olho de Basilisco'), 8.00),
((SELECT id FROM monsters WHERE nome='Elemental de Fogo'), (SELECT id FROM items WHERE nome='Cinzas Vulcânicas'), 55.00),
((SELECT id FROM monsters WHERE nome='Elemental de Fogo'), (SELECT id FROM items WHERE nome='Escama de Salamandra'), 25.00),
((SELECT id FROM monsters WHERE nome='Salamandra Gigante'), (SELECT id FROM items WHERE nome='Cinzas Vulcânicas'), 55.00),
((SELECT id FROM monsters WHERE nome='Salamandra Gigante'), (SELECT id FROM items WHERE nome='Escama de Salamandra'), 25.00),
((SELECT id FROM monsters WHERE nome='Demônio Menor'), (SELECT id FROM items WHERE nome='Cinzas Vulcânicas'), 55.00),
((SELECT id FROM monsters WHERE nome='Demônio Menor'), (SELECT id FROM items WHERE nome='Escama de Salamandra'), 25.00),
((SELECT id FROM monsters WHERE nome='Golem de Magma'), (SELECT id FROM items WHERE nome='Cinzas Vulcânicas'), 55.00),
((SELECT id FROM monsters WHERE nome='Golem de Magma'), (SELECT id FROM items WHERE nome='Escama de Salamandra'), 25.00),
((SELECT id FROM monsters WHERE nome='Fênix Selvagem'), (SELECT id FROM items WHERE nome='Cinzas Vulcânicas'), 55.00),
((SELECT id FROM monsters WHERE nome='Fênix Selvagem'), (SELECT id FROM items WHERE nome='Escama de Salamandra'), 25.00),
((SELECT id FROM monsters WHERE nome='Fênix Selvagem'), (SELECT id FROM items WHERE nome='Pena de Fênix'), 8.00),
((SELECT id FROM monsters WHERE nome='Lich'), (SELECT id FROM items WHERE nome='Pó de Lich'), 55.00),
((SELECT id FROM monsters WHERE nome='Lich'), (SELECT id FROM items WHERE nome='Elmo de Cavaleiro da Morte'), 25.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro da Morte'), (SELECT id FROM items WHERE nome='Pó de Lich'), 55.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro da Morte'), (SELECT id FROM items WHERE nome='Elmo de Cavaleiro da Morte'), 25.00),
((SELECT id FROM monsters WHERE nome='Dragão Ancião'), (SELECT id FROM items WHERE nome='Pó de Lich'), 55.00),
((SELECT id FROM monsters WHERE nome='Dragão Ancião'), (SELECT id FROM items WHERE nome='Elmo de Cavaleiro da Morte'), 25.00),
((SELECT id FROM monsters WHERE nome='Demônio Maior'), (SELECT id FROM items WHERE nome='Pó de Lich'), 55.00),
((SELECT id FROM monsters WHERE nome='Demônio Maior'), (SELECT id FROM items WHERE nome='Elmo de Cavaleiro da Morte'), 25.00),
((SELECT id FROM monsters WHERE nome='Guardião Ancestral'), (SELECT id FROM items WHERE nome='Pó de Lich'), 55.00),
((SELECT id FROM monsters WHERE nome='Guardião Ancestral'), (SELECT id FROM items WHERE nome='Elmo de Cavaleiro da Morte'), 25.00),
((SELECT id FROM monsters WHERE nome='Guardião Ancestral'), (SELECT id FROM items WHERE nome='Escama de Dragão Ancião'), 8.00);
-- ================= BOSS EQUIPMENT DROPS =================
INSERT INTO monster_drops (monster_id, item_id, chance_drop) VALUES
((SELECT id FROM monsters WHERE nome='Aranha Gigante Pequena'), (SELECT id FROM items WHERE nome='Espada Curta'), 10.00),
((SELECT id FROM monsters WHERE nome='Aranha Gigante Pequena'), (SELECT id FROM items WHERE nome='Colete de Couro'), 10.00),
((SELECT id FROM monsters WHERE nome='Aranha Gigante Pequena'), (SELECT id FROM items WHERE nome='Colar de Osso'), 10.00),
((SELECT id FROM monsters WHERE nome='Bandido Florestal'), (SELECT id FROM items WHERE nome='Martelo de Guerra'), 10.00),
((SELECT id FROM monsters WHERE nome='Bandido Florestal'), (SELECT id FROM items WHERE nome='Cota de Malha'), 10.00),
((SELECT id FROM monsters WHERE nome='Bandido Florestal'), (SELECT id FROM items WHERE nome='Anel de Prata Simples'), 10.00),
((SELECT id FROM monsters WHERE nome='Águia Gigante'), (SELECT id FROM items WHERE nome='Espada Longa'), 10.00),
((SELECT id FROM monsters WHERE nome='Águia Gigante'), (SELECT id FROM items WHERE nome='Armadura de Ferro'), 10.00),
((SELECT id FROM monsters WHERE nome='Águia Gigante'), (SELECT id FROM items WHERE nome='Brinco de Jade'), 10.00),
((SELECT id FROM monsters WHERE nome='Crocodilo Gigante'), (SELECT id FROM items WHERE nome='Espada de Aço'), 10.00),
((SELECT id FROM monsters WHERE nome='Crocodilo Gigante'), (SELECT id FROM items WHERE nome='Armadura de Aço'), 10.00),
((SELECT id FROM monsters WHERE nome='Crocodilo Gigante'), (SELECT id FROM items WHERE nome='Colar de Turquesa'), 10.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro Caído'), (SELECT id FROM items WHERE nome='Martelo Sagrado'), 10.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro Caído'), (SELECT id FROM items WHERE nome='Armadura Sagrada'), 10.00),
((SELECT id FROM monsters WHERE nome='Cavaleiro Caído'), (SELECT id FROM items WHERE nome='Amuleto Rúnico'), 10.00),
((SELECT id FROM monsters WHERE nome='Ladrão do Deserto'), (SELECT id FROM items WHERE nome='Katana do Vento'), 10.00),
((SELECT id FROM monsters WHERE nome='Ladrão do Deserto'), (SELECT id FROM items WHERE nome='Vestes do Sábio'), 10.00),
((SELECT id FROM monsters WHERE nome='Ladrão do Deserto'), (SELECT id FROM items WHERE nome='Anel do Campeão'), 10.00),
((SELECT id FROM monsters WHERE nome='Harpia Congelante'), (SELECT id FROM items WHERE nome='Lança da Tempestade'), 10.00),
((SELECT id FROM monsters WHERE nome='Harpia Congelante'), (SELECT id FROM items WHERE nome='Armadura Flamejante'), 10.00),
((SELECT id FROM monsters WHERE nome='Harpia Congelante'), (SELECT id FROM items WHERE nome='Colar Dracônico'), 10.00),
((SELECT id FROM monsters WHERE nome='Basilisco'), (SELECT id FROM items WHERE nome='Katana Negra'), 10.00),
((SELECT id FROM monsters WHERE nome='Basilisco'), (SELECT id FROM items WHERE nome='Armadura do Dragão Negro'), 10.00),
((SELECT id FROM monsters WHERE nome='Basilisco'), (SELECT id FROM items WHERE nome='Colar Flamejante'), 10.00),
((SELECT id FROM monsters WHERE nome='Fênix Selvagem'), (SELECT id FROM items WHERE nome='Lâmina Divina'), 10.00),
((SELECT id FROM monsters WHERE nome='Fênix Selvagem'), (SELECT id FROM items WHERE nome='Couraça do Deus da Guerra'), 10.00),
((SELECT id FROM monsters WHERE nome='Fênix Selvagem'), (SELECT id FROM items WHERE nome='Amuleto Cósmico'), 10.00),
((SELECT id FROM monsters WHERE nome='Guardião Ancestral'), (SELECT id FROM items WHERE nome='Lâmina de Selune'), 10.00),
((SELECT id FROM monsters WHERE nome='Guardião Ancestral'), (SELECT id FROM items WHERE nome='Armadura de Selune'), 10.00),
((SELECT id FROM monsters WHERE nome='Guardião Ancestral'), (SELECT id FROM items WHERE nome='Colar de Selune'), 10.00);

-- ================= CLASSES =================
INSERT INTO classes (nome, descricao, hp_base, mana_base, ataque_base, armadura_base, hp_regen_base, hp_regen_por_nivel, mana_regen_base, mana_regen_por_nivel) VALUES
('Guerreiro', 'Combatente resistente, focado em dano físico e defesa.', 30, 10, 12, 5, 8, 0.5, 0, 0),
('Mago', 'Conjurador frágil, com dano mágico alto e pouca vida.', 18, 40, 6, 1, 0, 0, 4, 0.3),
('Clérigo', 'Suporte com foco em cura e mana, resistência mediana.', 22, 35, 8, 3, 4, 0.2, 3, 0.2),
('Arqueiro', 'Ataques precisos à distância, equilíbrio entre dano e mana.', 22, 20, 10, 2, 6, 0.3, 2, 0.15);

-- ================= HABILIDADES =================
INSERT INTO habilidades (classe_id, nome, descricao, nivel_requerido, custo_mana, tipo, valor, duracao_turnos, cooldown_turnos) VALUES
-- Guerreiro
((SELECT id FROM classes WHERE nome='Guerreiro'), 'Golpe Poderoso', 'Um ataque com força extra.', 1, 5, 'dano', 15, 0, 1),
((SELECT id FROM classes WHERE nome='Guerreiro'), 'Grito de Guerra', 'Aumenta o ataque por alguns turnos.', 5, 8, 'buff_ataque', 6, 3, 2),
((SELECT id FROM classes WHERE nome='Guerreiro'), 'Postura Defensiva', 'Aumenta a armadura por alguns turnos.', 10, 8, 'buff_armadura', 8, 3, 3),
((SELECT id FROM classes WHERE nome='Guerreiro'), 'Fúria Implacável', 'Um golpe brutal, com alto dano.', 15, 12, 'dano', 35, 0, 4),

-- Mago
((SELECT id FROM classes WHERE nome='Mago'), 'Mísseis Arcanos', 'Projéteis de energia arcana.', 1, 10, 'dano', 18, 0, 1),
((SELECT id FROM classes WHERE nome='Mago'), 'Escudo Arcano', 'Um escudo mágico temporário.', 5, 12, 'buff_armadura', 10, 3, 2),
((SELECT id FROM classes WHERE nome='Mago'), 'Explosão de Gelo', 'Uma explosão gélida poderosa.', 10, 18, 'dano', 32, 0, 3),
((SELECT id FROM classes WHERE nome='Mago'), 'Meteoro', 'Invoca um meteoro devastador.', 15, 28, 'dano', 55, 0, 4),

-- Clérigo
((SELECT id FROM classes WHERE nome='Clérigo'), 'Toque Curativo', 'Cura uma quantidade de HP.', 1, 8, 'cura', 15, 0, 1),
((SELECT id FROM classes WHERE nome='Clérigo'), 'Bênção', 'Aumenta o ataque por alguns turnos.', 5, 10, 'buff_ataque', 7, 3, 2),
((SELECT id FROM classes WHERE nome='Clérigo'), 'Cura Maior', 'Cura uma grande quantidade de HP.', 10, 18, 'cura', 35, 0, 3),
((SELECT id FROM classes WHERE nome='Clérigo'), 'Luz Sagrada', 'Um raio de luz que causa dano.', 15, 20, 'dano', 30, 0, 4),

-- Arqueiro
((SELECT id FROM classes WHERE nome='Arqueiro'), 'Tiro Certeiro', 'Um disparo preciso.', 1, 6, 'dano', 16, 0, 1),
((SELECT id FROM classes WHERE nome='Arqueiro'), 'Chuva de Flechas', 'Múltiplos disparos rápidos.', 5, 10, 'dano', 24, 0, 2),
((SELECT id FROM classes WHERE nome='Arqueiro'), 'Foco Predatório', 'Aumenta o ataque por alguns turnos.', 10, 10, 'buff_ataque', 8, 3, 3),
((SELECT id FROM classes WHERE nome='Arqueiro'), 'Tiro Perfurante', 'Um disparo que ignora parte da armadura.', 15, 16, 'dano', 40, 0, 4);

-- ================= ITEMS: ARMAS INICIAIS =================
INSERT INTO items (nome, tipo, valor, nivel_requerido, raridade, descricao, dano) VALUES
('Espada de Treino', 'Arma', 25, 1, 'Comum', 'Espada básica usada por guerreiros novatos.', 5),
('Cajado Iniciante', 'Arma', 25, 1, 'Comum', 'Cajado simples que canaliza magia básica.', 6),
('Arco Curto', 'Arma', 25, 1, 'Comum', 'Arco leve usado por arqueiros iniciantes.', 5),
('Talismã Sagrado', 'Arma', 25, 1, 'Comum', 'Talismã abençoado usado por clérigos novatos.', 4);

-- ================= CIDADES =================
INSERT INTO cidades (nome, regiao, descricao) VALUES
('Elaris', 'Planície', 'Capital das Planícies Centrais, conhecida por seus mercados movimentados.'),
('Valdoren', 'Floresta', 'Cidade élfica erguida entre as árvores da Floresta Sombria.'),
('Khar-Dûm', 'Montanha', 'Fortaleza anã escavada nas Montanhas, famosa por sua ferraria.'),
('Sah''Rakar', 'Deserto', 'Cidade-oásis no coração do Deserto Ardente.'),
('Nocthar', 'Ruínas', 'Assentamento erguido sobre as Ruínas Amaldiçoadas, envolto em mistério.');

-- ================= EVENTOS =================

INSERT INTO events (nome, tipo) VALUES
('Combate Direto', 'combate_direto'),
('Acampamento Inimigo', 'acampamento'),
('Descanso', 'descanso'),
('Coleta', 'coleta');
('Baú', 'achado'),
('Saco Abandonado', 'achado'),
('Câmara do Tesouro', 'achado'),
('Estátua', 'achado');
('Veio de Minério', 'coleta'),
('Cristais Raros', 'coleta'),
('Cristais de Gelo', 'coleta'),
('Cristais de Magma', 'coleta');
('Pegadas', 'pegadas'),
('Eco Misterioso', 'investigacao'),
('Sala Secreta', 'achado'),
('Ruínas', 'investigacao');
('Armadilha', 'risco'),
('Lava Ativa', 'risco'),
('Gêiser de Magma', 'risco'),
('Rocha Vulcânica', 'risco'),
('Portal', 'portal');
('Altar Antigo', 'cura'),
('Fonte Mágica', 'cura'),
('Santuário', 'cura');

-- ================= LOCATION EVENTS =================

INSERT INTO location_events (location_id, event_id, peso) VALUES
-- Pradaria Inicial (ND 1) — zona tranquila, pouco acampamento
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Combate Direto'), 45),
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 8),
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Descanso'), 22),
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Coleta'), 25),
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Baú'), 10),
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 10),
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Pegadas'), 10),
((SELECT id FROM locations WHERE nome='Pradaria Inicial'), (SELECT id FROM events WHERE nome='Armadilha'), 10),

-- Floresta Sombria (ND 2) — tema de "Acampamento Goblin", muita coleta (ervas/cogumelos/árvore)
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Combate Direto'), 42),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 13),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Descanso'), 15),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Coleta'), 30),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Baú'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Estátua'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Câmara do Tesouro'), 1),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Madeira/Resina de Árvore Gigante'), 1),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Pegadas'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Eco Misterioso'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Sala Secreta'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Ruínas'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Armadilha'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Altar Antigo'), 8),
((SELECT id FROM locations WHERE nome='Floresta Sombria'), (SELECT id FROM events WHERE nome='Santuário'), 1),

-- Colinas Rochosas (ND 3) — mina/veio de minério, acampamento de bandidos
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Combate Direto'), 48),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 12),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Descanso'), 10),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Coleta'), 30),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Baú'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Câmara do Tesouro'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Veio de Minério'), 12),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Cristais Raros'), 1),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Cristais de Gelo'), 1),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Veio de Gemas'), 1),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Pegadas'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Eco Misterioso'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Sala Secreta'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Ruínas'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Armadilha'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Fonte Mágica'), 8),
((SELECT id FROM locations WHERE nome='Colinas Rochosas'), (SELECT id FROM events WHERE nome='Altar Antigo'), 8),

-- Pântano Nebuloso (ND 4) — ervas raras, sem flavor de acampamento nos eventos citados
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Combate Direto'), 50),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 8),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Descanso'), 12),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Coleta'), 30),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Baú'), 8),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 8),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Estátua'), 8),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Madeira/Resina de Árvore Gigante'), 2);
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Pegadas'), 14),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Eco Misterioso'), 8),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Ruínas'), 8),
((SELECT id FROM locations WHERE nome='Pântano Nebuloso'), (SELECT id FROM events WHERE nome='Armadilha'), 8),

-- Masmorra Abandonada (ND 5) — esqueleto/zumbi combinam com acampamento; pouca coleta natural
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Combate Direto'), 55),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 15),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Descanso'), 10),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Coleta'), 20),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Baú'), 15),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 18),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Câmara do Tesouro'), 15),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Armadilha'), 14),
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Portal'), 2),

-- Deserto Ardente (ND 6) — ladrão do deserto é literalmente do bioma
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Combate Direto'), 50),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 15),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Descanso'), 10),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Coleta'), 25),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Baú'), 8),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 8),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Pegadas'), 8),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Ruínas'), 8),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Armadilha'), 8),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Fonte Mágica'), 8),
((SELECT id FROM locations WHERE nome='Deserto Ardente'), (SELECT id FROM events WHERE nome='Santuário'), 3),

-- Montanhas Geladas (ND 7) — cristais de gelo = coleta; clima hostil, pouco acampamento
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Combate Direto'), 50),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 10),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Descanso'), 15),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Coleta'), 25),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Baú'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Câmara do Tesouro'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Veio de Minério'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Cristais Raros'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Cristais de Gelo'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Veio de Gemas'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Pegadas'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Eco Misterioso'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Sala Secreta'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Ruínas'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Armadilha'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Fonte Mágica'), 8),
((SELECT id FROM locations WHERE nome='Montanhas Geladas'), (SELECT id FROM events WHERE nome='Altar Antigo'), 8),

-- Caverna de Cristal (ND 8) — cristais raros/veio de gemas = coleta; monstros, não bandidos
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Combate Direto'), 55),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Descanso'), 12),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Coleta'), 25),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Baú'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Câmara do Tesouro'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Veio de Minério'), 12),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Cristais Raros'), 16),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Cristais de Gelo'), 16),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Veio de Gemas'), 12),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Pegadas'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Eco Misterioso'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Sala Secreta'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Ruínas'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Armadilha'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Fonte Mágica'), 8),
((SELECT id FROM locations WHERE nome='Caverna de Cristal'), (SELECT id FROM events WHERE nome='Altar Antigo'), 8),

-- Vulcão Adormecido (ND 9) — hostil demais pra descansar/coletar à vontade
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Combate Direto'), 60),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 10),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Descanso'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Coleta'), 22),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Baú'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Estátua'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Câmara do Tesouro'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Cristais de Magma'), 10);
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Sala Secreta'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Ruínas'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Armadilha'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Lava Ativa'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Gêiser de Magma'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Rocha Vulcânica'), 8),
((SELECT id FROM locations WHERE nome='Vulcão Adormecido'), (SELECT id FROM events WHERE nome='Altar Antigo'), 8),

-- Ruínas Amaldiçoadas (ND 10) — endgame, esqueleto/zumbi combinam com acampamento, pouco espaço pra coleta
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Combate Direto'), 60),
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Acampamento Inimigo'), 12),
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Descanso'), 8),
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Coleta'), 20);
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Baú'), 15),
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Saco Abandonado'), 18),
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Câmara do Tesouro'), 15);
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Ruínas'), 8);
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Armadilha'), 14),
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Portal'), 2);
((SELECT id FROM locations WHERE nome='Masmorra Abandonada'), (SELECT id FROM events WHERE nome='Santuário'), 3),
((SELECT id FROM locations WHERE nome='Ruínas Amaldiçoadas'), (SELECT id FROM events WHERE nome='Santuário'), 3);